### ISSUE TITLE
Notification Tray

### ISSUE THREAD

**Issue by grahamPegNetwork** [regolith-linux/regolith-desktop#1]
Add system tray support for applications/services that provide applets. Coming from i3 I typically keep blueman-applet and nm-applet running, however with i3blocks it appears that neither of these display. This is something supported in i3 and feels like a step in the wrong direction.

**Comment by kgilmer** [comment]
Thanks for your feedback @grahamPegNetwork , and congrats on being first to file an issue against Regolith!  I see your point and yeah you're absolutely right that the tray is not available w/ i3blocks and i3bar.  In earlier prototypes of Regolith I used [Polybar](https://github.com/jaagr/polybar) instead of i3bar which has built-in support for the tray.  IMHO, the tray interface is dated and the nm-applet UI is inconsistent with what I'd describe as the modern GNOME UI.  I also could not theme it consistently with the other components.  Due to this and a desire for less stuff on the screen, I opted instead to rely on gnome-settings for wifi, bt, etc..  The UI is more expansive, keyboard driven, centralizes most management and configuration, and in my opinion just a better experience.  A primary design choice I made with Regolith is to avoid the bar for active configuration tasks.  It is true however that you must launch the settings app rather than having the options readily available via the tray.  It is my opinion that it's an acceptable price to pay given the stated benefits of gnome-settings.

In any case, if you should like a tray it's not hard to swap out i3bar for polybar.  [Here](https://github.com/kgilmer/Regolith-Desktop-Environment/blob/deprecation-snapshot/packages/regolith-config/regolith-config/configs/i3/i3-gaps.config#L132) is the integration between i3 and polybar.  Here is a Regolith-style [polybar config](https://github.com/kgilmer/Regolith-Desktop-Environment/blob/deprecation-snapshot/packages/regolith-config/regolith-config/configs/polybar/polybar.config) that includes a tray, and [here](https://github.com/kgilmer/Regolith-Desktop-Environment/blob/deprecation-snapshot/packages/regolith-config/regolith-config/scripts/polybar-launcher.sh) is the script that is required to launch polybar.

**Comment by grahamPegNetwork** [comment]
Cool, thanks for the info @kgilmer . I'll take a look at polybar to see if it meets my needs. I understand the perspective of the tray interface being dated. Whene I think about it the only thing I actively use would be wireless and bluetooth management. (For those, having a tray icon is more convenient than launching a program for configuration) Beyond that I have also used sync clients in the past (Seafile, Dropbox, etc) which benefit from a tray icon, (eg: quick sync pausing) and of course too many applications that simply "want" an icon but don't need one. 

(out of scope) I'm not sure how far you will be taking this, but what may be a good option is if somebody were to build a new, clean configuration..."bar" or something which supported applets (enable/disable on demand) and was primarily focused on things such as networking/bluetooth, maybe sound/brightness. As much as I dislike it, I think Windows...10? started using a slide out bar on the right for that type of behaviour. I could see some sort of pop up configuration tool in my future, which could be clicked or naturally, bound to a hotkey. But I digress...

Anyways, still using Regolith, seems to be a prettier/cleaner arrangement than my old i3 with minor tradeoffs.

**Comment by kgilmer** [comment]
@grahamPegNetwork I definitely understand where you're coming from with the ad-hoc quick configuration use cases.  In my estimation, the place for wifi and these sorts of common things is not in the bar, but rather inside of Rofi.  Here is how I categorize UI components in Regolith:

Passive, read-only information: bar
Notifications: bar (currently a pop up window hosted by gnome-flashback.  See #8 )
User directives: Full-screen modal (Rofi)

I think an ideal form of the Regolith UI would be to reduce everything down to the bar and rofi (or something like it.)

*However* I am used to thinking of these settings as either "control panel" style (ala gnome-settings), or as bar applets as you prefer.  I haven't been able to come up w/ a full screen modal design that would allow a user to carry out the interactive steps in setting up a wifi, etc., nor do I think it would be very easy to do so.  One thing that's great about the gnome-settings is that a whole lot of work went into making it work well.  It would be difficult to have that same level of quality without some serious dev effort.

Getting back to a more customizable bar, yes I have thought about that as well.  In fact most of my time in customizing Regolith has been spent on the bar.  I have spent some time with experimental changes to i3bar, but didn't come up with anything compelling enough to favor it over what the i3wm and i3gaps projects have done.  But, for a future version of Regolith, I am considering either writing a bar from scratch or make a version of i3bar that delegates almost everything to lua scripts, including blocks, workspace visualization, and maybe some kind of transition animations as are common now on mobile UIs.  I would certainly be interested in any work you do in this area!

In looking at bar implementations available, it becomes apparent to me where the complexity lies: in expressing rich visual layout of information (eg css/html), and providing a configuration language (eg polybar.config).

**Comment by kgilmer** [comment]
Closing this issue as there is no action to be done.  Of note: the new keybindings for settings like Bluetooth and Wifi.  This reduces the workflow to change wifi networks or setup a bluetooth device to a single keybinding and then whatever UI action is necessary in the control center.

**Comment by justyn** [comment]
I'm new to i3 and regolith, but after reading this issue I thought that i3bar didn't support the system tray.

But after installing regolith I have added the line `tray_output primary` to my `bar {}` section in i3 config and now I have a system tray containing the applets for programs that provide them.

So actually system tray is supported, or have I misunderstood?

**Comment by kgilmer** [comment]
Hi @justyn , you're right: system tray is supported.  The reason this issue was opened is that someone felt that the tray should be enabled by default, rather than having to configure i3 to enable it.

**Comment by justyn** [comment]
Oh ok, I had understood the issue to be the belief that the system tray isn't supported with i3blocks.

**Comment by viter** [comment]
How can I make system tray icons look according to the bar theme? They are just black color on white background.

**Comment by kgilmer** [comment]
Hi @viter , I do not personally use the system tray and so don't have much to offer.  But, I suggest opening a separate issue or asking in Slack so that others may see your question and provide some suggestions.  If you find a solution let us know! :smile:

**Comment by 0atman** [comment]
Hi @kgilmer, thanks for all your work on Regolith, big fan except for this bug!
(I'm commenting on bug #1 somewhat symbolically, sorry if there's an open bug for this. Given that Regolith doesn't ship with this enabled, I guess you still feel the same way)

**I think you've made the wrong design decision here.**

The tray is part of the Free Desktop specification (https://specifications.freedesktop.org/systemtray-spec/systemtray-spec-0.2.html) and many programs in the linux ecosystem **can't work** without one. (e.g. Sparkleshare, the gnome project).

To be clear, I am not suggesting enabling the tray for bad features like `nm-applet`, I agree with your decision to integrate them into the bar, that's very nice. Nor am I asking for instructions, your very clear documentation shows how it should be done.

Users (and freedesktop.org) expect a conforming DE to have a tray. **Regolith must ship with it enabled**, like i3 does by default.

**Comment by kgilmer** [comment]
Hi @0atman ,

  Thanks for your well reasoned argument and the link to the tray specification.  I skimmed it but didn't find anything in it that supports the assertion:

> Users (and freedesktop.org) expect a conforming DE to have a tray

  Can you provide any links that go into detail regarding this DE expectation?

**Comment by justyn** [comment]
I thought I'd weigh in, though I've no idea if anyone has done a study on this, it's quite a niche question.

I certainly expected a tray when I first used Regolith (and I still have the tray enabled, and find it useful for certain apps).

My personal opinion that if Regolith is geared partly towards people who haven't used a "non-standard" desktop before, having the tray on by default would make for a smoother onboarding for some of them.

Also, since you don't have any applets in the default Regolith configuration, it would be empty anyway on install. It would only populate if the user installed an app that expected the tray. So it seems pretty low cost.

**Comment by 0atman** [comment]
@kgilmer Thanks for getting back to me. I regret my use of _conforming_ in my previous comment, suggesting that there is _One DE Specification To Rule Them All_. As you might expect, it's an a-la-carte approach, whereby one can take whatever components and mix your own DE, as you have done with Regolith. To make matters worse, there's the indicator specification that Ubuntu and KDE use.

SO the tray isn't required in the freedesktop specification, I withdraw that part my assertion, apologies for my assumption.

HOWEVER:

That users expect a DE to have a tray, there can be no doubt, and I would suggest that application developers (we're talking gnome and kde and the other DEs), ALSO expect a tray/indicator to exist.

I like the way @justyn put it: **A default Regolith install will have no icons in the tray, so if the user never uses apps that use it, they'll never see it. Why not enable it for the people that do?**

**Comment by 0atman** [comment]
Oh! I forgot to mention this. The reason I think that users and app developers expect a tray is that it is available for use in default configurations of nearly every distro's DEs, such as:
 - Ubuntu's Gnome (the most popular desktop that new and power user alike will be familiar with
 - KDE, all flavours
 - Mint, all flavours
 - Fedora/red hat
 - And, the most clear of them all: **i3's default is to enable the tray**.

I just installed to confirm this for myself:
![Screenshot from 2020-07-31 16-36-47](https://user-images.githubusercontent.com/114097/89051973-ef100080-d34c-11ea-9b27-d070e29beb51.png)

**Comment by kgilmer** [comment]
I did some investigation and could not find a significant runtime cost (RAM usage) to enabling the tray vs disabled.  Based on this and the perspectives provided in this ticket,  we will change this default behavior to enable the system indicator (aka notification) tray by default in the next version of Regolith.  Thanks to everyone here that took the time to provide feedback!  :smile:

**Comment by 0atman** [comment]
Wonderful! Thank you so much @kgilmer :-)

**Comment by newptcai** [comment]
I still do not see a dropbox icon in the bar even if it is running. In regolith's i3 config there is

~~~
bar {
  tray_output $i3-wm.bar.trayoutput
}
~~~

Is there anything which I can do to show a dropbox icon in the bar?
