### ISSUE TITLE
SolArc theme missing

### ISSUE THREAD

**Issue by gigglearrows** [regolith-linux/regolith-desktop#112]
After upgrading regolith (I had the Solarized-Dark theme), I noticed the new default theme had changed to Nordic. I changed it back to theme-regolith in .Xresources-regolith. It could not find the SolArc theme, because it was not installed, so I had to install it manually. It works fine now, but im not sure if this was just an upgrade issue (that it uninstalled the theme during upgrade), or if you actually forgot to install that theme as a dependency when installing regolith for the first time.

**Comment by kgilmer** [comment]
It was intentional.  The theme is still in the PPA but I opted to remove it from the dependencies as it's not the default theme.  I agree it's not the best experience to have to remember to install whatever package is required for a theme to work.  I opted to remove it to save space on the user's computer for files they (probably) won't use.  Do you think it would be better to keep it installed?  Something else?

**Comment by gigglearrows** [comment]
Alright, I see!

**Comment by gigglearrows** [comment]
imo, I still think it should be a dependency since we still have it commented out in the default config file. Or at least add a comment in the config file that a dependency should be installed before trying out the theme
