### ISSUE TITLE
regolith-desktop was uninstalled on upgrade

### ISSUE THREAD

**Issue by p3k** [regolith-linux/regolith-desktop#114]
just returned from two weeks of vacation and ran apt dist-upgrade just to find no i3 desktop being displayed afterwards.

i remembered to see an apt message about `regolith-desktop` (and another package) to be removed (which i probably did not think much about due to being jetlagged).

in fact, the package was missing and after reinstalling it regolith is back again. (of course without my custom i3 config settings again, unfortunatetly. but that’s a different story.)

any ideas why such a fundamental error could happen? let me know if i could provide more information.

**Comment by kgilmer** [comment]
Hi @p3k :smile: .  I cannot think if a reason that `regolith-desktop` would be removed by a dist-upgrade.  The only thing that should have been removed is `regolith-i3` (as it's be replaced by `i3-gaps-wm`).  You can look at the logs in `/var/log/apt`, in the history and term logs for clues as to what may have happened.  If you find anything interesting in there feel free to post it here.

**Comment by kgilmer** [comment]
Also, regarding your older configuration, this table may help how to get that hooked back up: http://localhost:4000/configuring.html#config-files

**Comment by p3k** [comment]
> Also, regarding your older configuration, this table may help how to get that hooked back up: https://regolith-linux.org/configuring.html#config-files

yes, i have seen that. i copied my custom settings into `~/.config/regolith/i3/config` and reloaded i3 but they are not applied. should there be something like an include statement in `/etc/regolith/i3/config`? (i don’t see any.)

is there a log output which config files are getting read?

**Comment by p3k** [comment]
regarding tHe config it seems it was applied after reboot. HoweVer, tHe i3bar Has disappeared now (and my H and V keys only work witH sHift, er…)

crazy.

**Comment by kgilmer** [comment]
Regarding "i copied my custom settings into ~/.config/regolith/i3/config and reloaded i3 but they are not applied", yes when this happens you must log back in because reloading i3 simply reloads it as-is.  It won't take new the config script.  Other users have also run into this and I believe someone is going to submit a PR to update the documentation to be more clear.

Regarding the log file, yes it certainly shows that regolith-desktop is to be removed, although it doesn't mention why.  I have been able to reproduce this behavior in testing.  I'll keep an eye out however, and see if I can search around for more clues.

Regarding config after reboot, really there are two files that Regolith will override with defaults if exist:
1. `~/.Xresources-regolith`
2. `~/.config/regolith/i3/config`

If you move or remove these files then upon next login, you should have a stock configuration and everything should work.  If you put those files back and experience the issues, there is probably a mismatch between the stock files and your configuration.  I would suggest diffing them in this case and look for variable name changes, etc..

**Comment by p3k** [comment]
> If you have the package `regolith-gdm3-theme` and you didn't install it manually then you probably installed from the LiveCD.

yup i got that.

> Regarding the i3 config file, it either loads the version in `~/.config/regoilth/i3/config` or if that does not exist, `/etc/regolith/i3/config`

ok makes sense. i now re-added the missing settings from `/etc/regolith/i3/config` to the user config file (also restored the X settings into `~/.Xresources-regolith`) and almost everything looks the way as before again. yay!

(i think i understand now why some of the keys on my keyboard where not working: without the `$mod` variable it seems the key was remapped without any modifier key, and thus e.g. an unsuspecting `v` did not output the expected letter but immediately set the container to vertical alignment – the intended behaviour for `$mod+v` in my b0rked custom settings.)

_almost_ because e.g. i changed the date format in the i3bar ; what is the recommended way to override such a setting now? (afair i changed it directly in the `i3xrocks/time` file before…)

anyway, thanks a lot for your great assistance and further investigation. i am somehow glad you could verify the removal of `regolith-desktop`, although it’s certainly a nasty issue.

**Comment by kgilmer** [comment]
@p3k , to update the date format in the i3bar, change the value defined here: https://github.com/regolith-linux/regolith-styles/blob/master/Xresources/i3xrocks#L8.  However, keep in mind that you'll need to copy the default Xresources definition into your user directory to make the change.  I've updated [this page](https://regolith-linux.org/configuring.html) to describe that in better detail.

**Comment by p3k** [comment]
alright got it… the i3xrocks file was still around in my user dir, all i had to do is change the reference in `~/.Xresources-regolith` again.

so that solves the configuration quirks after the upgrade. 

regarding the original issue i leave it up to you @kgilmer whether you want to track this down further or close this issue, resp.

as always, thanks for your help.

**Comment by kgilmer** [comment]
Glad to hear you've got everything fixed up and thanks for your patience in dealing w/ all of these changes to Regolith.  I've created a separate issue to track the dist-upgrade thing: https://github.com/regolith-linux/regolith-desktop/issues/120
