### ISSUE TITLE
Graphical issues after update

### ISSUE THREAD

**Issue by Custards1** [regolith-linux/regolith-desktop#116]
opening any apps, particualary the terminal, causes that app to flicker and nearly be unreadable. issue also happens with cpu load percentage on the lower bar

**Comment by zerotao** [comment]
I'm experiencing the same issue. I swapped back to the prior compton config and it appears, at least for the moment, to have gone back to normal.

**Comment by kgilmer** [comment]
Thanks for the feedback @zerotao .  If that continues to work for you LMK and I'll add a note on the site regarding the issue for others.

**Comment by zerotao** [comment]
@kgilmer the old config continues to work without flicker. I have been going thru the new config line-by-line when I have time but, as of yet, have not found the culprit(s).

**Comment by kgilmer** [comment]
Awesome, will be good to know what the root cause is @zerotao :smile: .

**Comment by zerotao** [comment]
@kgilmer  For the last two days, I have been running the current config with `use-damage = false`, which appears to have solved the problem in my case (Nvidia drivers). I did try turning `use-damage = true` in the old configs; it did not reproduce the flicker in that case which leads me to believe there is some interaction between multiple config items causing the actual issue.

I will continue to pick away at it. @Custards1 could you try setting use-damage=false in your config and see if it removes the issue for you?

**Comment by kenanbit** [comment]
Modifying compton to `use-damage = false` solved [the flickering](https://www.youtube.com/watch?v=Bp25Fyy_GsI&feature=youtu.be) for me. That's not my video, but the issue is exactly the same for me. It affects many types of windows. It seems like a flickering of historical window states.

 Here's more info in case it's useful:

I installed regolith for the first time on a fresh Ubuntu install 6 days ago, and the flicker started once I installed the `nvidia-340` driver and rebooted. Purging that driver to switch back to `nouveau` is how I temporarily solved the issue. 

I previously ran Arch Linux + i3 + nvidia-340 on the same laptop without the flickering issue.

I changed compton to `use-damage = false` today, reinstalled nvidia-340, and rebooted: no flickering. Thanks for finding this!

**Comment by thebeardbe** [comment]
Just to add to the issue, I had the flickering also. 

Kubuntu 19.04 Latest update
Nvidia 430 drivers

Added the ```use-damage = false ``` also, no flickering.

However I still have on some apps. like libreoffice calc other windows draw over it after switching virtual desktop. It disappears when the window needs to redraw for ie. scrolling. It only occurs on switching not during use of the app.

**Comment by lawzava** [comment]
Started facing flickering after the last update. `use-damage = false` does not help. Disabling compton fixes the issue. No GPU.

**Comment by kgilmer** [comment]
Related https://github.com/regolith-linux/regolith-desktop/issues/156

**Comment by georgbuechner** [comment]
After having installed regolith-20.04.0-1.4-desktop-amd64.iso both on my desktop and my laptop I am experiencing the flickering too. However I cannot find `use-damage` or `compton` in `/etc/regolith/i3/config`

**Comment by BridgeTrollPW** [comment]
@georgbuechner I did a `locate compton.conf` and returned `/etc/xdg/xdg-xubuntu/compton.conf` as path. I assume use-damge should be put there, as a `man compton` also shows `--use-damage` as an option, so my assumption is use-damage should go into the compton.conf file. Take this with a grain of salt tho, I didn't really have any flickering/graphical issues so I can't test if this is correct or not

**Comment by georgbuechner** [comment]
Thank you for the fast response. So I set `use-damage = false;` in `/etc/xdg/xdg-xubuntu/comton.conf` but it didn't seem to have an effect on the flickering. 
Is it correct to simply but `use-damage` anywhere in the config? Will it be automatically loaded after reboot? 
Flickering is really annoying. I would love to get some help on this. If there is any additional information I can provide, I'm happy to do so! 

Graphics: GeForce GTX 960

**Comment by kgilmer** [comment]
The location for a custom compton config is described here: https://regolith-linux.org/docs/customize/compositors/#overriding-a-compositor-configuration.  Once changing you'll need to log back in for it to take effect.

A faster way to make changes and see the result would be to just kill the compton process and load it manually to test changes:

```bash
$ pkill compton
$ /usr/bin/compton -f --config /tmp/myconfig.conf
```

**Comment by georgbuechner** [comment]
Thanks a lot, that helped! 
So changing the compton config-file works similar to changing the i3 config: `To provide your own Compton/Picom compositor config, copy the default or create your own and save it as ~/.config/regolith/compton/config. Upon next session it will be loaded instead of the default config /etc/regolith/compton` (https://regolith-linux.org/docs/customize/compositors/#overriding-a-compositor-configuration.)
The changing `use-damage = true;` to `use-damage = true;` did the trick. 
Thanks a lot.

**Comment by kgilmer** [comment]
Glad you've resolved your issue @georgbuechner , but for my understanding, did you mean to make one of these different?

> The changing use-damage = true; to use-damage = true; did the trick.

**Comment by georgbuechner** [comment]
@kgilmer I'm so sorry. Of course I change it to `use-damage = false;` I've edited my comment, thanks for letting me know.

**Comment by mattdibi** [comment]
Experienced the same issues to the point the terminal was unusable. `use-damage = false` setting had minor effects. Resorted to disabling compton entirely from inside i3 configuration.

This issue helped me a lot in diagnosing the problem.

System informations:
```
OS: Ubuntu 19.10 x86_64 
Host: All Series 
Kernel: 5.3.0-51-generic 
Shell: zsh 5.7.1 
Resolution: 2560x1440, 1920x1080 
DE: GNOME 3.34.3 
WM: i3 
Theme: Ayu-Mirage-Dark [GTK2/3] 
Icons: Moka [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-4790K (8) @ 4.600GHz 
GPU: NVIDIA GeForce GTX 1070 
Memory: 2470MiB / 15955MiB
```

**Comment by vivz753** [comment]
`pkill compton` solved it right away for me! Thank you so much, the flickering was driving me crazy. I was experiencing screen shaking (most notably in the gnome terminal--in the browser, there's a bit of flickering in the type cursor but not as bad as half pages or lines completely not showing on the terminal). It only happens on Regolith after installation of nvidia proprietary drives (don't even get me started, this took me like 6+ hours to figure out... such a hassle disabling and enabling a bunch of crap). I completely rely on Regolith for my daily usage, thank you!

Specs:
OS: Ubuntu 18.04 LTS x86_64
GPU: NVIDIA GeForce GTX970

**Comment by kgilmer** [comment]
Thanks to everyone providing their graphics hardware and driver details.  Based on what we've got so far, it appears that nvidia and compton are not getting along.  

There has been some updates to compton recently (now called Picom).  Once I get the time to package it, perhaps someone is able to test w/ their systems to see if previous problems are now fixed?  I'll update this ticket with more information when I have it.

**Comment by krishnachaitanya9** [comment]
`pkill compton` did it for me. I run regolith in Pop! OS with Nvidia RTX 2070 graphics. When I used to normally run some command, the output of the command didn't appear immediately. To get around it many times I used to make the terminal window lose focus momentarily and then give focus back to it to see the output of the command. After executing the aforementioned command, I see no such lag and everything runs smoothly as it runs in my default gnome-desktop. So I can agree that compton can be the issue. I will update my answer after observing for a couple of days. Thank you!

**Comment by kgilmer** [comment]
@krishnachaitanya9 thanks for the details :smile: .  You can make the removal of compton permanent by installing `regolith-compositor-none` if you like.

**Comment by krishnachaitanya9** [comment]
Ahh! That's way better. I was killing the process on every reboot. Thank you so much @kgilmer :grinning:

**Comment by kgilmer** [comment]
You're very welcome @krishnachaitanya9 .  Also, [this page](https://regolith-linux.org/docs/customize/compositors/) covers other options in detail.  We're in the process of packaging up the latest version of picom (v8) so that should be available in a week or two and may give you visual effects without the glitches.

**Comment by krishnachaitanya9** [comment]
Thank you so much for your great support @kgilmer, I will surely check out for picom. Thank you!

**Comment by ankitson** [comment]
I had the flickering issues and  traced the problem to a bug in picom i described here:

https://github.com/yshui/picom/issues/268#issuecomment-642448574

It seems yshui fixed it [here](https://github.com/yshui/picom/commit/cbe34158f3a364ff87bce948c787e0383e0b0c54#diff-facacfb5d72224a496b34279f2da0c11), one day after releasing v8/stable, so the fix is on the `next` branch ;)

As a workaround, you can also launch compton/picom with `--xrender-sync-fence`, then it will work even with `use-damage=true`. Atleast in my case, i had the same flickering symptoms and they disappear either with the extra flag or running picom compiled from the next branch.

**Comment by kgilmer** [comment]
Thanks @ankitson !  Actually picom v8 (release) is now in Regolith unstable.  I'm running it now.  I'll look into adding the work around flags you mention to the default Regolith picom config.

**Comment by agoose77** [comment]
I can confirm that adding the `xrender-sync-fence` flag (or config option) fixes the flickering for me on Ubuntu 20.04, with an Nvidia (driver 440). Thanks all!

**Comment by kgilmer** [comment]
I will push this change to `regolith-compositor-compton-glx` in the `unstable` PPA for user testing.  Thanks for the feedback @agoose77 :smile:

**Comment by gservat** [comment]
@kgilmer should https://github.com/regolith-linux/regolith-compositor-compton-glx/commit/d9a4da6f84955ea2cc38354e964d9fd08fa92047#diff-2245023265ae4cf87d02c8b6ba991139R45 end with a semi-colon?

**Comment by kgilmer** [comment]
Whoops, thanks @gservat !

**Comment by kgilmer** [comment]
To prevent misunderstanding, can you kindly provide the patch here that is working for you @jijeshmohan ?

**Comment by jijeshmohan** [comment]
sorry for the confusion. I applied this https://github.com/regolith-linux/regolith-compositor-compton-glx/commit/d9a4da6f84955ea2cc38354e964d9fd08fa92047#diff-2245023265ae4cf87d02c8b6ba991139R45 in my configuration

**Comment by GavinRay97** [comment]
@krishnachaitanya7 @kgilmer Thank you for the `pkill compton` and `regolith-compositor-none` advice!
I too am on Pop_OS 20.04 and Nvidia RTX 2060 (hybrid graphics, mixed with AMD Renoir integrated).

Always had weird stutter/lag-behind in `drun` and on my other laptop (Ubuntu 20.04, Nvidia GTX-1060Ti) the default terminal broke from stuttering so bad that I had to install an external GPU-rendered terminal app.

`pkill compton` fixed it immediately :pray: I had been living with this for like a year :joy:

**Comment by acebone** [comment]
Same problem, same fix.

What is the compton (or picom) compositor actually used for in Regolith? I see no difference?

**Comment by kgilmer** [comment]
@acebone compton should not be running if you installed `regolith-compositor-none`.  I guess that if you're still seeing compton, then there is an init script or maybe your i3 file is loading it.

> What is the compton (or picom) compositor actually used for in Regolith? I see no difference?

If you don't notice a difference then not having it is probably your best bet.  It provides some shadowing for windows, transparency, and depending on the compositor and it's configuration, can address screen tearing issues if you have them.

**Comment by acebone** [comment]
Yes, I wasn't observant enough, I use at semitransparent background in my
windowed bash-shell, and of course it's not transparent any more.

I will have to run through my scripts, I must admit that I am a guy who
configures a lot of bells and whistles, before quite grasping how a system
really works. The i3 way of doing things has a lot of patterns that are a
tad unfamiliar to me, or at least. they seem to be.

**Comment by dylanwright** [comment]
I also experienced this issue with the following specs:
Regolith Desktop 1.4.1
Ubuntu 20.04
GeForce 2070 (NVIDIA Studio Driver)

```pkill compton``` fixed it immediately
```regolith-compositor-none``` package sucessfully persisted the change after reboot.

Thanks!

**Comment by swansinflight** [comment]
Ryzen5 3600, 5700XT GPU, fresh Regolith install from ISO. Immediate flickering, found this issue so copied compton config to `~/.config/regolith/compton/config` and added `use-dmg = false` and it fixed the flickering issue.

**Comment by acebone** [comment]
I tried it - unfortunately it didn't work for me.

**Comment by acebone** [comment]
> I tried it - unfortunately it didn't work for me.



> Ryzen5 3600, 5700XT GPU, fresh Regolith install from ISO. Immediate flickering, found this issue so copied compton config to `~/.config/regolith/compton/config` and added `use-dmg = false` and it fixed the flickering issue.

I tried it - unfortunately it didn't work for me.

**Comment by potaito** [comment]
I have the same issues. 
My hardware: 
Lenovo X1 Extreme (2nd gen)
GPU: Nvidia Geforce GTX1650

On installation, I had to use the Safe Graphics boot option (adds `nomodeset` to startup command in grub), otherwise I would get pixel junk and the computer was unusabe.

Then after installing the proprietary `nvidia-driver-450` I started getting a jumpy and jittery terminal. Especially processes with lots of output like `apt get update` would produce a terminal that was barely readable. When using `nano` the terminal would also flicker to the point where I could not tell whether I am still inside Nano or not. And worst of all. When entering a password in the terminal, which should be invisible, the jitter would actually reveal the password. My password was then visible in the terminal window's history until I closed the window.

Step 1: Kill compton with `pkill compton` completely removed the problem. 
Step 2 will be trying to figure out a middle path with `use-dmg = false`...

**Comment by acebone** [comment]
The `--xrender-sync-fence` option does the trick!

From Comptons manpage: 

`--xrender-sync-fence
           Use X Sync fence to sync clients' draw calls, to make sure all draw calls are finished before compton starts drawing. Needed on nvidia-drivers with GLX
           backend for some users.`

So it's not a regolith-issue at all, but a known glitch between Compton and the nvidia-driver.

I'd like to suggest that the regolith-install-procedure checks for the nvidia-driver, and if found adds the --xrender-sync-fence option to "`exec compton`" line

**Comment by potaito** [comment]
> I'd like to suggest that the regolith-install-procedure checks for the nvidia-driver, and if found adds the --xrender-sync-fence option to "`exec compton`" line

That's going to be tricky, since the Nvidia drivers are optional since they are proprietary. The OS installation will always use the nouveau drivers by default, which don't have this issue with Compton. The user then has to install the Nvidia drivers manually.

**Comment by acebone** [comment]
True, on the other hand, a lot of users will install regolith AFTER the nvidia-drivers, if not most users. You could also check for hardware rather than drivers - or perhaps just use the option no matter what hardware/driver people have. I'm pretty sure that other drivers will not be affected in any noticeable way by that option.

Another path could be to simply warn any user of nouveau or nvidia-drivers, that they might have to edit their regolith config file, and add the option themselves.

**Comment by kgilmer** [comment]
Another option would be to create a variant of `regolith-compositor-compton-glx` specific for modern nvidia hardware + proprietary driver.  However, FWIW in Regolith will ship with picom by default (`regolith-compositor-picom-glx`) which is much more recent, and may not need anything specific for various hw or driver varations.  In any case, if users are able to come up with some settings that are better than the default and a few people can test them, I'm happy to package those settings to make it easier for others.

Strategies such as modifying system files based on hw configuration is likely out of scope for a project like Regolith, due to the amount of testing that such logic requires across hardware and OS variants.
