### ISSUE TITLE
Request for Comment: Make ISO install more minimal 

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#157]
While Regolith is not trying to be a super minimal distro that is designed to support old, low powered hardware, it is certainly striving to reduce the visual clutter of the desktop.  However some users have expressed surprise at how many apps ship as part of the LiveCD.  Others have suggested that default apps be removed altogether, and that some backend subsystems such as Snap be removed to save drive space and reduce overall complexity.  On the other hand, tracking closely to Ubuntu means that Regolith behaves more like Ubuntu and will provide less surprise for those used to or expecting an experience like Ubuntu.

If you have an opinion on this issue, give a thumbs up/down or provide more detailed feedback as a comment. This RFC will be open until Nov 15 2019.

**Comment by ploum** [comment]
My take is that it all boils down to the intended users. I see two extreme cases of users:

1. Casual users, who don't know how to install new apps (nor what to install). For those users, having lot of app by default is paramount as it give them features without asking them to make a choice.

2. Advanced users, who know what they want and are able to install what they need. They will also remove what they don't need.

Assumption: by essence, Regolith users are in the second category. I assume that anybody confortable with a keyboard driven tiling manager is able to use apt-get. In fact, Regolith already makes such an assumption by putting the terminal as the most accessible app. There's also no option to "explore" what is currently installed (no menu, no icon).

If that assumption is correct, it means that every regolith user know what she want to install and how to do it. It also means that, most probably, there's no way to satisfy a large userbase with a set of default: everybody has different needs. 

Assumption 2:  users of category 2. often tends to want a "clean" system and will remove what is not needed (to save disk space, to not have unwanted processes in the background and to make upgrade faster).

Assumption 3: Most regolith users have access to a fast internet and don't rely on the default install to have software otherwise too big to download.

If my 3 assumptions are correct, I would argue that the conclusion is that Regolith should provide the minimal working system so it can be installed in a fast and easy way without needing to "clean and configure" afterward.

Writing this, I also realise that allowing a regolith user to easily save and restore her own config might be a goal (like making a clean install and immediately restoring settings to have your own environement in a few minutes).

**Comment by brandondees** [comment]
IMO it should be rare for i3 users to _not_ understand that they can `apt install` whatever common apps they want to use. I think the important contribution of a distribution package like regolith is that it helps offloads from the end user all of the more tricky configuration, testing, debugging types of issues involved in using the tools and configs that are not standalone windowed applications (namely i3, menus, theming, system configuration tweaks, etc)

For the case of bandwidth-constrained, or offline users, a secondary package of "all the other bundled/tested stuff" could be handy, but... I'm not sure how common that is, nor how to guess at what regolith's user base will consider necessary for a fully functional system. For my own purposes, I'd be more interested in tools to make it easier to craft my own live disk with the preinstalled apps I choose.

I also agree with all of the above from @ploum, I'd like my base install to include nothing I don't use, but everything that I do use (you can't predict this, and it changes over time), so i'm happy with starting from a relatively clean base and configuring my own dotfiles to install my go-to standalone things, and my desired customization over the base install.

**Comment by kgilmer** [comment]
Thanks for the feedback!  It will be referenced as part of the R1.3 release.
