### ISSUE TITLE
Feature: allow different compositors and compositor configurations to be easily swapped

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#175]
Reasoning: Users have different preferences about how much visual effects they prefer.  Also, various computer hardware responds differently to various backends and configurations.  

Acceptance Criteria: A user should be able to use the packaging system to swap compositors and not have to deal with hand editing files.  It should "just work".

**Comment by kgilmer** [comment]
This shipped in 1.3.

**Comment by jr0cket** [comment]
I started having lagging issues with the cursor and buffer refreshes with Emacs 26.3 on Ubuntu 19.04, after moving to Regolith 1.3 (from 1.2).  I believe Regolith 1.3 made the issue more noticeable, but then there were also changes in how some Emacs packages worked too (particularly Magit).

I assumed there was some issue with the default Compton compositor, so changed to the `regolith-compositor-none` and the issue is gone.  I don't believe I use any desktop compositor effects, so I assume I am not missing anything important.  I will also give the xcompmgr a try sometime.

Thank you for creating the alternative compositor packages, incredibly useful.

**Comment by kgilmer** [comment]
Hi @jr0cket , the one aspect you may miss without a compositor is the elimination of screen tearing during video playback.  This is also possibly handled at other layers in the stack, depending on your hardware and driver setup.  So you may or may not experience screen tearing without a compositor.  Keep in mind as well that there may be changes to the default config for compton/picom that address your issue.

**Comment by jr0cket** [comment]
@kgilmer the only minor issue I've had with the 'no-compositor' so far is my screenshot tool when selecting a region, so nothing important.  I will try the other compositor and have a look through some options for picom compositor, but every I need to work is working so far.

I also saw some discussion about nvida driver version 430 causing issue, https://github.com/yshui/picom/issues/283 so will also try updating the nvida driver at some point too.
