### ISSUE TITLE
Add i3 config keybinding search order to wiki

### ISSUE THREAD

**Issue by dahadaller** [regolith-linux/regolith-desktop#183]
The [HowTo: Add or change i3 Keybindings](https://github.com/regolith-linux/regolith-desktop/wiki/HowTo:-Add-or-change-i3-Keybindings) should link to a separate wiki page that explains in what order config files are searched for keybindings in regolith.

I've found at least 5 config files on my own system (not sure if this list is complete)
- `/etc/i3/config` and `/etc/i3/config.keycodes`
- `~/config/regolith/i3/config`
- `~/config/i3/config`
- `~/config/i3-reglith/config`

**Comment by kbknapp** [comment]
Mine also has `/etc/regolith/i3/config`

**Comment by kgilmer** [comment]
Thanks for the feedback @dahadaller :smile: .   This information is contained in https://github.com/regolith-linux/regolith-desktop/wiki/Customize.  IMHO it's not clear that these details are of top priority to those reading the HowTo page you link.  Feel free to edit the page if you'd like to.

FWIW all that matters in R1.2 is `/etc/regolith/i3/config` (default) and `~/.config/regolith/i3/config`, and [here is the logic](https://github.com/regolith-linux/regolith-gnome-flashback/blob/master/i3-gnome-flashback#L4-L14).

**Comment by kgilmer** [comment]
Also, it's worth noting that the structure of the wiki is inconsistent in places and information is at times redundant, vague, and misleading.  This is mainly due to the information moving from the static site months back without a proper rewrite.  I've made a post R1.3 release [task](https://github.com/regolith-linux/regolith-desktop/issues/185) to spend some time on cleanup.
