### ISSUE TITLE
Errors after upgrade

### ISSUE THREAD

**Issue by meatballs** [regolith-linux/regolith-desktop#193]
After ubuntu (19.10) updated the regolith package (2.45-1ubuntu1~ppa3), I now get an error that `~/rofi_theme.rasi` does not exist when I try to launch an app.

**Update**
I have a workaround using a symlink pointing to `/etc/regolith/rofi/regolith-theme.rasi`

(Also, shift-cmd-? no longer toggles the help window).

**Comment by kgilmer** [comment]
Ah, you are running from `regolith-unstable` and there has been additions to the Xresources that are not included in your user copies I'm guessing.  Compare `/etc/regolith/styles/root` with `~/.Xresources-root` and `/etc/regolith/i3/config` with `~/.config/regolith/i3/config`, or if you just want to get it working, rename the files mentioned above that are in your user directory to something else and log back in so that Regolith will load the defaults in `/etc`.

**Comment by kgilmer** [comment]
In particular, Rofi configurations are now associated with a "look" (AKA theme), and live in places like `/etc/regolith/styles/cahuella/rofi.rasi` (for the Cahuella look).

Also, thanks for helping to test `regolith-unstable`!

**Comment by meatballs** [comment]
Ah yes. That was from when I was first trying to get things working on 19.10. Thank you.
