### ISSUE TITLE
How to change fonts?

### ISSUE THREAD

**Issue by shashank-k** [regolith-linux/regolith-desktop#252]
How to change fonts in st terminal.

**Comment by kgilmer** [comment]
Hi @shashank-k , see this tutorial for changing the font: https://regolith-linux.org/docs/howto/terminal-font/

FYI, the upcoming version of Regolith 1.3.1 has a simplified approach to basic configuration that simply requires creating a single file with a single line to override the font value, rather than creating a custom style as described in the link above.

**Comment by shashank-k** [comment]
Thanks!
Is there any date planned for 1.3.1 release?

**Comment by kgilmer** [comment]
As a volunteer effort, Regolith isn't able to set specific delivery dates.  However you can track progress of the release here: https://github.com/orgs/regolith-linux/projects/10
