### ISSUE TITLE
R1.3.1 Launch Plan

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#260]
```
[X] Test PPA migration from release and r1.3 to unstable on eoan and bionic
[X] Verify new features work as expected in migrated instances
[X] Fix any bugs
[X] Update website w/ new release notes and changes to docs as needed
* Styles
* Remontoire
* App associations
* Date/time locale
* Update wallpapers using Rofi and Remontoire, add one for new dark wallpaper.
* Update keybindings page
[X] Once no bugs, sync unstable to stable and release
[ ] Generate R1.3.1 ISOs for bionic and eoan
[ ] Upload media to sourceforge
[X] Mailing list and twitter announcement
[ ] go ride the bike
```

**Comment by benabhi** [comment]
Very good work @kgilmer! Please continue to improve Regolith in my opinion the most beautiful and USEFUL distribution to date: D and the one I plan to continue using for a good time since it fits exactly with my workflow. I will continue testing and notifying any possible bug or new ideas to keep this amazing project up to date.

❤️ Regolith!

**Comment by kgilmer** [comment]
Thank you for the good vibes and feedback @benabhi !  And yes, keep it coming :smile:

**Comment by kgilmer** [comment]
Remaining work for this has been moved to R1.4.
