### ISSUE TITLE
Keybinding Help Not Working

### ISSUE THREAD

**Issue by skostojohn** [regolith-linux/regolith-desktop#284]
Just upgraded to 1.3 on Ubuntu 18.04.

I noticed that the keybindings help is not working....  Super+Shift+? does nothing, and clicking on the bar icon yields this:
![image](https://user-images.githubusercontent.com/2495345/77334623-4dafd880-6ce2-11ea-8cb3-442780d7dd09.png)

When I first upgraded, I got an "file not found" error message from rofication-gui.py line 76 - but it hasn't reappeared and I don't know if it is related.  I'll capture it and add it to the issue if it reappears.

Love regolith and 1.3 feels like a great upgrade, but would love to figure out how to fix this issue.  Thanks in advance for any help!

Scott

**Comment by kgilmer** [comment]
Hi Scott, you upgraded from a previous release? to 1.3 or 1.3.1?  which PPA?  do you have a custom i3 or Xresources files?  What does `i3 --moreversion` print?

**Comment by skostojohn** [comment]
Thanks for the quick reply!
Yes, I upgraded from a prior release.  
Here is the PPA I am using: http://ppa.launchpad.net/regolith-linux/release/ubuntu bionic
I am not sure about the custom i3/xresources files - it has been some time since I installed regolith desktop, and I am not sure if I modified any of these files - sorry.
Here is what i3 --moreversion prints:
![image](https://user-images.githubusercontent.com/2495345/77336078-47baf700-6ce4-11ea-89f4-b07f4d59a3d3.png)

**Comment by kgilmer** [comment]
Ok, got it.  The reason that the shortcuts are blank is because now the shortcut UI reads directly from i3 rather than hardcoding the keybindings.  In order to make this work, the format of comments in the i3 config file were modified.  You have a custom i3 config file so you don't have the updated comments, and so the shortcuts are empty.  

To fix this, you'll need to abandon your custom i3 config in `~/.config/regolith/i3/config` or merge your i3 file with the latest default in `/etc/regolith/i3/config`.

To verify my assertions without risk:
1. `mv ~/.config/regolith/i3/config ~/.config/regolith/i3/config-backup`
2. log out / back in
3. <super>? should now show shortcuts
4.  `mv ~/.config/regolith/i3/config-backup ~/.config/regolith/i3/config`
5. log out / back in and system is restored to your existing configuration.

**Comment by skostojohn** [comment]
That was it.
When I renamed my config file to config-backup and logged out/in, everything was working perfectly.

I looked through the config-backup and didn't see anything I remembered/recognized, so I am just going to abandon it for now and move forward with the default.  At some point perhaps I will run into something that will remind me what I did in the original config.

Thanks so much for your quick assistance!
