### ISSUE TITLE
Wallpaper changes after i3 reset

### ISSUE THREAD

**Issue by insept** [regolith-linux/regolith-desktop#344]
Hi,
Running ubuntu 20.04 and just installed the latest version of Regolith.
I've changed the wallpaper via the gnome settings, but when I reset i3 (super+shift+r) the wallpaper changes back to the default one "ESP_016895_1525_desktop.jpg".
I searched the config file which I copied from /etc/regolith/i3/config but I can't see anything regarding wallpapers in that config.

**Comment by kgilmer** [comment]
Hi @insept , this is by design.  session refresh explicitly reloads the Xresource and i3 configuration from disk.  The setting you want is in Xresources, as `gnome.wallpaper`.  You can search through the existing Xresource data w/ `xrdb`, for example:

```bash
$ xrdb -query | grep background
gnome.wallpaper:	/usr/share/backgrounds/ESP_016895_1525_desktop.jpg
i3-wm.bar.background.color:	#1F2430
i3-wm.bar.workspace.active.background.color:	#BFBAB0
i3-wm.bar.workspace.focused.background.color:	#FFA759
i3-wm.bar.workspace.inactive.background.color:	#BFBAB0
i3-wm.bar.workspace.urgent.background.color:	#FF3333
i3-wm.client.focused.color.background:	#BFBAB0
i3-wm.client.focused_inactive.color.background:	#292B30
i3-wm.client.unfocused.color.background:	#292B30
i3-wm.client.urgent.color.background:	#FF3333
```

In order to specify your own background image that will survive a session refresh, override the default value, like this:

```bash
$ echo "gnome.wallpaper: absolute-path-to-image" >> ~/.config/regolith/Xresources
```

More information is available here: https://regolith-linux.org/docs/howto/override-xres/

Kindly re-open the issue if it's unclear or something doesn't work as expected.

**Comment by fisuku** [comment]
I came across this issue with updated Regolith. I don't think it's a good design decision given Regolith seems to be designed around combining i3 with the Gnome UIs.

Now there is a settings panel which works for one thing (the lock screen) but not for another (the wallpaper). Is the plan to slowly phase the Gnome settings panel out entirely?

**Comment by kgilmer** [comment]
Hi @fisuku :smile: .  There is no plan to get rid of gnome settings.  Regolith tries to honor both Xresource and GNOME settings for wallpaper.  It does this by only updating from Xresources if something in the Xresource settings changed since the last login session.  If nothing has changed, the wallpaper should not update.  If you change the wallpaper via Settings, this has no effect on Xresources.  So, you should be able to manage your wallpaper either via Xresources or Settings.  However, if you make **any** changes to Xresources, Regolith will see this the next time you login and refresh the UI based on Xresources.  In the next point release I will add an optional Xresource flag that will cause Regolith to always ignore Xresource values for gtk theme, icon theme, and wallpaper for users that prefer to just use the gnome settings to manage their UI.  

This behavior isn't perfect but the best I could come up with at present.  Please let me know if you have any ideas to improve it!  :smile:
