### ISSUE TITLE
Ubuntu 20.04 Screen lock bug

### ISSUE THREAD

**Issue by Ralphhorn** [regolith-linux/regolith-desktop#356]
OS: Ubuntu 20.04
Regolith Unstable

After installing regolith I experienced some problems related to locking my screen.
If I lock my screen I do get a password prompt asking me for a password. However once I login the UI does not seem to load. However, I am able to reboot or shutdown my desktop with the standard regolith keybinds.

Any help would be appriciated, I am somewhat new to I3/regolith.

**Comment by FischerMoseley** [comment]
Can confirm, I'm having the same issue on a fresh install of 20.04 running on an XPS 15 9570.

**Comment by kgilmer** [comment]
@Ralphhorn can you check if the package `gnome-screensaver` is installed?  The version of `gnome-flashback` (the variant of Gnome used by Regolith) has integrated the lock screen into itself as of the 20.04 version, and so there may be some kind of race or conflict.  Another common issue w/ screen refresh issues is due to a problem with video hardware and the compositor.  You can test if this is the problem by installing the package `regolith-compositor-none` and then logging back in.

That @FischerMoseley is having the same issue on a fresh install is concerning.

Is it true that when in the bad state, the computer is running fine, but the UI does not update at all?  what if you switch to a TTY?  <ctrl><alt>F6, for example...does it do anything?

**Comment by kgilmer** [comment]
Also, @Ralphhorn I suggest you switch to the release or stable PPA now that the 1.4 release is official.  Unstable is...well, not always a great place to be.  To switch your PPA:

```bash
$ sudo add-apt-repository --remove ppa:regolith-linux/unstable
$ sudo add-apt-repository ppa:regolith-linux/release
```

**Comment by ssauperl** [comment]
I have the same problem on the regolith release, ubuntu 20.04.

**Comment by Ralphhorn** [comment]
@kgilmer `gnome-screensaver` is installed. I will remove it tonight and check if this does solve the problem. I will also switch to the stable branch.

Would you recommend testing the TTY before removing gnome-screensaver?

@ssauperl My setup uses one ultrawide monitor so it seems that this issue might not be exclusive to multi-monitor setups

**Comment by kgilmer** [comment]
> Would you recommend testing the TTY before removing gnome-screensaver?

If possible, yes.  If not NBD.

**Comment by xfalcox** [comment]
Installing `regolith-compositor-none` don't solve the issue.

**Comment by tobybatch** [comment]
On a dual screen setup only one screen unlocks, the other is still locked.

I can fix it by ```killall gnome-flashback && gnome-flashback &``` if that's any help.

**Comment by xfalcox** [comment]
<kbd>Super</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd> also helps.

**Comment by muktupavels** [comment]
There was some problems with screensaver in `gnome-flashback`. Please try/test 3.36.3 release that has few fixes for it. If new release does not fix problems, then get debug output for screensaver - `G_MESSAGES_DEBUG=screensaver gnome-flashback`.

**Comment by kgilmer** [comment]
Thanks @muktupavels , where can we get that version of `gnome-flashback`?  I searched launchpad.net but didn't find it.

**Comment by muktupavels** [comment]
https://gitlab.gnome.org/GNOME/gnome-flashback/-/tags

It is not available in Ubuntu yet. I also need to create SRU bug first...

**Comment by Ralphhorn** [comment]
> > Would you recommend testing the TTY before removing gnome-screensaver?
> 
> If possible, yes. If not NBD.

Some stuff came up and I could not test it at the planned time. 
It seems that I can lock my screen and log back in if I immediately enter the password. However, Once I leave it locked for a while I can not see my UI. 

However, If I remove the gnome-screensaver I cannot lock the session.
What would be used for the session lock?

These are my current session lock configs.
`## Session // Lock Screen // <> Escape ##
set_from_resource $i3-wm.program.lock i3-wm.program.lock gnome-screensaver-command --lock

bindsym $mod+Escape exec $i3-wm.program.lock
`

**Comment by kgilmer** [comment]
@Ralphhorn looks like you're using an old version of the Regolith i3 config file.  [This is what the keybinding](https://github.com/regolith-linux/regolith-i3-gaps-config/blob/master/config#L277-L279) should execute in R1.4.  I suggestion you reset your install back to defaults and then reintegrate any desired changes once you get the default working.

https://regolith-linux.org/docs/getting-started/install/#upgrading-with-customizations

**Comment by Ralphhorn** [comment]
Works like a charm!

**Comment by muktupavels** [comment]
https://bugs.launchpad.net/ubuntu/+source/gnome-flashback/+bug/1876731

**Comment by felisucoibi** [comment]
same here, lot of computers, gnome-flashback installed, screen saver lock never comes back

**Comment by prouddad1** [comment]
Related problem:  Upgraded from 18.04 to 19.10 in March after a processor upgrade.  Screen lock stopped working at all.  Switch was there in the settings, but didn't activate screen lock.  Super + L did nothing. CNTRL + ALT + L did nothing.   Upgraded to 20.04 a couple of days before the official release, hoping that would resolve the issue.  Still same problem.  Only way to lock the screen is to do a shutdown.  Not really a solution but NVMe makes it bearable.

**Comment by prouddad1** [comment]
Related problem:  Upgraded from 18.04 to 19.10 in March after a processor upgrade.  Screen lock stopped working at all.  Switch was there in the settings, but didn't activate screen lock.  Super + L did nothing. CNTRL + ALT + L did nothing.   Upgraded to 20.04 a couple of days before the official release, hoping that would resolve the issue.  Still same problem.  Only way to lock the screen is to do a shutdown.  Not really a solution but NVMe makes it bearable.  
Update:  I ran:  **`gnome-screensaver-command -l`**
Now Super + L works

**Comment by sbakic** [comment]
Hi @kgilmer I am confused now.

Since I installed Ubuntu 20.04 as an upgrade of 19.10 (everything worked fine with 19.10, even 19.04 and 18.10 - this was upgrade path through the years), with all default settings related to UI environment and so on, I couldn't lock the screen. What I mean by that is basically clicking on the lock screen at the bottom right corner or lock screen shortcut give the same output, which is freezing the whole window for 2-3 seconds and then returning back to normal window, without locking it. Nothing happens when I set timer to lock the screen as well.

At first, I  thought it is some bug and that they will resolve it at some point.

I am not familiar with any package that locks the screen in Ubuntu. So I don't know where to start to investigate this issue.

What I have run:

`dm-tool lock`
Command 'dm-tool' not found, but can be installed with:
sudo apt install lightdm

`gnome-screensaver-command -l`
Command 'gnome-screensaver-command' not found, but can be installed with:
sudo apt install gnome-screensaver

`dpkg -l | gnome-flashback`
Command 'gnome-flashback' not found, but can be installed with:
sudo apt install gnome-flashback

`sudo dpkg-reconfigure gdm3`
no output

`ps -ef | grep 'screensaver'`
sbakic      2513    2098  0 10:35 ?        00:00:00 /usr/libexec/gsd-screensaver-proxy
sbakic      5965    3955  0 10:41 pts/0    00:00:00 grep --color=auto screensaver

As I understood I don't have `lightdm` or `gnome-screensaver` which is used to lock the screen. I didn't read much about `gnome-flashback`, I didn't understand what it is.

**What should I install and do I need to configure something?**

Thanks

**Comment by kgilmer** [comment]
Hi @Ralphhorn , it appears that Regolith was uninstalled as part of your Ubuntu upgrade.  This is expected, [see here](https://regolith-linux.org/docs/getting-started/install/#upgrading-ubuntu) about steps to add Regolith back into your system.

**Comment by sbakic** [comment]
As I understood this command lock the screen but it doesn't work. How can I debug it?

`dbus-send --type=method_call --dest=org.gnome.ScreenSaver /org/gnome/ScreenSaver org.gnome.ScreenSaver.Lock`

**Comment by prouddad1** [comment]
In my case, gnome desktop replaced unity.  I had to run the gnome command
for screenlock in terminal the first time, then it worked as expected
(settings and hot keys worked).  This also worked to launch terminal with
hot keys.  I had to manually run the commands in terminal before they would
work with hot keys.

**Comment by prouddad1** [comment]
@stefan  The settings or hot key didn't have any effect when first upgrade
to 19 in FEB2020.  Revisit the issue after upgrade to 20.04 MAY2020 I
encountered the same problem.  I opened a terminal and used the terminal
command for lock screen (gnome) and lock screen worked.  Hot key command
started working after this as well.

**Seems like the command has to be executed from terminal once and the
problem was resolved.**

I had the same experience getting terminal to launch from hot key.  After
issuing the command in terminal once, the hot keys to launch terminal
worked.

**Comment by Ralphhorn** [comment]
> Hi @Ralphhorn , it appears that Regolith was uninstalled as part of your Ubuntu upgrade. This is expected, [see here](https://regolith-linux.org/docs/getting-started/install/#upgrading-ubuntu) about steps to add Regolith back into your system.
> 
> If this does not solve your problem, kindly open a new issue so we can take a look.

Hey @kgilmer, I have not been following this thread for a while due to trying out an arch based distro for the first time. Could it be that you meant to tag the previous poster?

**Comment by samigeorgiev** [comment]
Hi all,
What is the final solution of that bug?
