### ISSUE TITLE
issue with terminal GUI freezing

### ISSUE THREAD

**Issue by ItsChoudhry** [regolith-linux/regolith-desktop#370]
So in the terminal when you run a command the terminal the GUI doesn't update sometimes until you press something or click. Here is a screenshot of what it looks like. I see with the issue with both installing from ubuntu and a direct iso of regolith too

![Screenshot from 2020-05-03 16-47-57](https://user-images.githubusercontent.com/23042676/80918692-34c52900-8d5e-11ea-84df-f643bfb7ed36.png)

**Comment by kgilmer** [comment]
Hi @ItsChoudhry :smile: .  Users with this sort of issue are typically having a problem with the compositor and their specific graphics driver/hw.  Switching or removing the compositor usually fixes it.  See here for details: https://regolith-linux.org/docs/customize/compositors/

I suggest installing `regolith-compositor-none`, log back in, and see if the problem persists.

**Comment by ItsChoudhry** [comment]
Yup that sorted it out. thanks

**Comment by unique-identifier** [comment]
I was running the latest Regolith before switching to Ubuntu 20.04 for an unrelated reason. I installed Regolith desktop as an alternate desktop for myself and noticed this issue came back again. In my case, the issue seemed to go away after I edited /etc/regolith/compton/config and set glx-copy-from-front to true. I don't know if it's particular to my laptop and the nvidia gpu it's using or not. Hope it helps someone else.
