### ISSUE TITLE
Warning on the post-install step of regolith-rofication 1.2.2-1

### ISSUE THREAD

**Issue by jensens** [regolith-linux/regolith-desktop#388]
**Describe the bug**

A warning is issued on the post-install step of regolith-rofication 1.2.2-1.

**To Reproduce**

`apt upgrade` to Regolith 1.4.1

or any step upgrading to regolith-rofication 1.2.2-1.

Then output is

```
Setting up regolith-rofication (1.2.2-1) ...(process:1099959): dconf-WARNING **: 11:43:54.414: failed to commit changes to dconf: Could not connect: Connection refused
```

All continues to the end.

**Expected behavior**

No warning.

**Installation Details**
 - Regolith Install Type: [ISO]
 - Regolith Version: [1.4.0 to 1.4.1]

**Additional context**

I report here b/c regolith-rofication has no issue tracker enabled.

**Comment by moritzheiber** [comment]
I can confirm this issue. It's likely caused by [the `postinst` action](https://github.com/regolith-linux/regolith-rofication/blob/master/debian/postinst#L6) in the `regolith-rofication` Debian package being executed in the wrong user's context (`root` instead of whatever user is running the upgrade)

**Comment by moritzheiber** [comment]
The relevant `postinst` has been removed. This should no longer occur.
