### ISSUE TITLE
[Feature Request] Calendar in i3xrocks block

### ISSUE THREAD

**Issue by stracedude** [regolith-linux/regolith-desktop#390]
Hi!
When you click on the time block it exec `/usr/bin/gnome-control-center datetime`. 
I think this is pretty useless behavior.
May be replace the time plugin in i3xrocks  on something like  https://github.com/vivien/i3blocks-contrib/tree/master/calendar.

**Comment by kgilmer** [comment]
Hi @stracedude , there is another request (https://github.com/regolith-linux/regolith-desktop/issues/352) to update the scripts so that users can easily override the default launch with something else.  I believe when this is ready you'll just be able to specify the program you wish to launch with a single Xresource overrride value.

**Comment by moritzheiber** [comment]
This is done: https://github.com/regolith-linux/regolith-i3xrocks-config/commit/2bfab21c15a9d730aaf9885bd777122f2ef72c16#diff-61593a7d2719aadce06d24a470345abb075417bbfd098da90286aa9b89c34310R44

**Comment by gbetous** [comment]
Hi,

On regolith Ubuntu 22.04 I still have the gnome-center which pops-up when I clik on the date, and seeing the patch above does not seem to resolve the issue. Can we reopen this issue ?

Thanks !

**Comment by kgilmer** [comment]
Hi @gbetous , did you override `i3xrocks.action.time` with the program you wish to launch?

**Comment by gbetous** [comment]
I thought that the proposed solution was "out of the box". I'll tune my scripts, thanks !
