### ISSUE TITLE
Disable auto-hiding mouse

### ISSUE THREAD

**Issue by XiovV** [regolith-linux/regolith-desktop#410]
How do I disable this feature? I'd like my mouse to stay on the screen instead of dissapearing as soon as it stops moving.

**Comment by moritzheiber** [comment]
You can unset the `Xresources` variable `i3-wm.program.unclutter` to disable `unclutter` and therefore "hiding" your cursor after a short while:
```
$ echo "i3-wm.program.unclutter:" >> .config/regolith/Xresources
```
Also, make sure the package `unclutter-startup` is not installed and/or hasn't left behind its configuration file from a prior install:

```
$ apt install unclutter-startup
$ apt remove --purge unclutter-startup
```

This will disable unclutter on your system permanently.

Reference: https://regolith-linux.org/docs/howto/override-xres/

**Comment by XiovV** [comment]
This fixed it, thanks.

**Comment by polaroidkidd** [comment]
I've followed these instructions but `unclutter` still runs at every start-up. 

Additionally, once ran the above commands, Ubuntu claimed that the following packages were no longer needed

```
i3xrocks-next-workspace libconfig9 libjsonrpc-glib-1.0-1 libxcb-composite0 libxcb-damage0 libxcb-ewmh2 moka-icon-theme picom regolith-compositor-picom-glx regolith-default-settings regolith-ftue regolith-gnome-flashback
  regolith-i3-gaps-config regolith-look-lascaille regolith-rofi-config regolith-styles regolith-unclutter-xfixes remontoire rofi x11-apps x11-session-utils xinit xorg
  ```

using `sudo apt autoremove -y` removed these packages, but after reboot I was unable to start a new session from login (which was kind of expected since it removed some core packages). I managed to fix it by `ctrl+alt+F1` and installing `regolith-desktop` again and rebooting again.

**Comment by kgilmer** [comment]
Hi @polaroidkidd ,

Can you respond w/ the output of the following commands?

`apt list --installed | grep unclutter`

`cat /etc/regolith/version`

**Comment by polaroidkidd** [comment]
thanks for looking into this. Here the results

```
➜ apt list --installed | grep unclutter

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

regolith-unclutter-xfixes/focal,now 1.5-2 amd64 [installed,automatic]

➜ cat /etc/regolith/version
REGOLITH_VERSION=1.6.0%
```
