### ISSUE TITLE
Unable to change the compositor manager or uninstall the gnome-terminal

### ISSUE THREAD

**Issue by ltadeu6** [regolith-linux/regolith-desktop#418]
**Describe the bug**
For some reason, if I try to change some default ubuntu packages regolith stops to work

**To Reproduce**
Remove the gnome-terminal or compton [unmaintained] and replace it with picom and then reboot.

**Expected behavior**
Work normally whitout this "dependencies"

**Installation Details**
 - Regolith Install Type: [PPA]
 - Regolith Version: [2.63]
 - PPA url: [ppa:regolith-linux/release]
 - Host OS (for PPA): [Ubuntu 20.04]

**Comment by moritzheiber** [comment]
`gnome-terminal` is the officially supported terminal of Regolith, so I'm not surprised there are a few things that aren't working when it's uninstalled (especially since `regolith-ftue` depends on it).

As for `compton`, we are using the officially supported and maintained fork of compton called `picom` (as you already mentioned). It's a little confusing, because of backward compatibility it's called `compton` instead of `picom`. You can find out more about compositors and how they're managed (and switched) in the documentation: https://regolith-linux.org/docs/customize/compositors/

Unless you've other remarks I'm marking this as invalid for now and going to close it tomorrow :slightly_smiling_face:
