### ISSUE TITLE
Increase hightlight of the window in focus

### ISSUE THREAD

**Issue by UtahDave** [regolith-linux/regolith-desktop#42]
Hi, Thanks so much for Regolith!  I've been using i3 for ~5 or 6 years now and the Gnome integrations in Regolith are so helpful.

I've been scouring the documentation and I haven't found a way to increase the indication of which application is in focus.  Basically, I'd like to make it more obvious that a specific application is currently in focus. Currently the application in focus is very subtly lightened.

Is there currently an option for this?

Thanks so much.

**Comment by UtahDave** [comment]
In the default config file I see this line:

```
client.focused          #002b36 #586e75 #fdf6e3 #268bd2
```

What exactly do these hex color values change?  Is this what I'm looking for?

**Comment by kgilmer** [comment]
Thanks for the kind words @UtahDave !  Those color values are documented in the (amazing) i3-wm user's guide.  The particular section you are looking for is here: https://i3wm.org/docs/userguide.html#_changing_colors

Please reopen the issue if you're not getting the change you expect.

**Comment by UtahDave** [comment]
For future reference, I wanted a stronger highlight of which window was in focus. Here's the settings I changed to get the desired behavior:

```
new_window pixel 4
new_float pixel 4
client.focused          #002b36 $blue #fdf6e3 #268bd2
```


Thanks again!

**Comment by kgilmer** [comment]
Thanks @UtahDave !  This is something others will want to tweak as well.  When I started out with i3 I had more of a contrast and then as I got used to things I dialed it down.  I've added your tip and other approach here: https://regolith-linux.org/howto.html#window-highlight-color

**Comment by coulix** [comment]
On the latest version, I ca not seem to make the opacity stronger so that I know which window is in focus when using super + arrows.

Changing those ```set_from_resource $i3-wm.bar.workspace.active.border.color i3-wm.bar.workspace.active.border.color "#073642"
set_from_resource $i3-wm.bar.workspace.active.background.color i3-wm.bar.workspace.active.background.color "#073642"
set_from_resource $i3-wm.bar.workspace.active.text.color i3-wm.bar.workspace.active.text.color "#586e75"

 ``` does not do much.

I was expecting an opacity parameter somewhere.
How does that work?

**Comment by kgilmer** [comment]
Hi @coulix , you can update the values in a variety of ways.  The standard way is to update the Xresource values for those keys.  They can be changed in `/etc/regolith/styles/i3wm`, and here is the [file in git](https://github.com/regolith-linux/regolith-styles/blob/R1.2/Xresources/i3-wm#L11).  [This page](https://github.com/regolith-linux/regolith-desktop/wiki/Customize) describes how to stage user versions of Xresource files so future updates don't overwrite your changes.   

Another simpler approach that will not be overwritten but is more direct would be to change the i3 file to use a literal value instead of an Xresource value.  So, rather than:
```
set_from_resource $i3-wm.bar.workspace.active.border.color i3-wm.bar.workspace.active.border.color "#073642"
```
You would do:
```
set $i3-wm.bar.workspace.active.border.color "#073642
```

**Comment by coulix** [comment]
I got what I was looking for in compton/config, the opacity part. Thank you!
