### ISSUE TITLE
Fresh install, in shell, ls -l etc is not working visually, most other commands are

### ISSUE THREAD

**Issue by yssoe** [regolith-linux/regolith-desktop#422]
I have a really strange issue. 

I don't have this in Ubuntu, only in Regolith, Video card is Quadro T2000

I have the resolution set to 3840x2160 with 200% scale 

When I type `ls -l` a few times, 2 out of 3 times it will display nothing but pressing enter will show empty lines, then once in a while, it does show it correctly, when i press ctrl-l to clear the screen i get put on the top of the terminal but the screen is not refreshed and empty it still shows the previous text. 

What I don't understand is this is not happening in Ubuntu 20.04, only in the regolith, I installed with the PPA as described on the site and switch between ubuntu and regolith on the login screen. 

I have downloaded and installed the ISO but it's the same error. 

Thanks!!

**Comment by kgilmer** [comment]
Hi @yssoe :smile: .  Sounds like perhaps a compositor issue.  Can you try installing `regolith-compositor-none` and see if the issue persists?  See https://regolith-linux.org/docs/customize/compositors/ for details on how to do that.

**Comment by yssoe** [comment]
@kgilmer  That fixed it !! Thanks, so it's a bug in the compositor? Am I missing a lot of beauty now? Should I file a bug report? 

Thanks for the help, as a long time dry i3 user, this regolith is so pretty and awesome. Thanks for your work.

**Comment by kgilmer** [comment]
Great, glad to hear it @yssoe.  I believe the issue is somewhere between your graphics card <-> driver <-> compositor.  There is another compositor you can use now for some of the visual effects like shadows: `regolith-compositor-xcompmgr`.  

Additionally, some people have reported success by changing the configuration of the default (comton/picom) compositor.  You can see details about that here: https://github.com/regolith-linux/regolith-desktop/issues/116

Also we'll be adding an updated picom compositor soon, which may be more robust to various hardware/driver configurations.  You can subscribe to the mailing list to learn when updates are available.
