### ISSUE TITLE
Battery not showing - Ubuntu 20.04

### ISSUE THREAD

**Issue by timgent** [regolith-linux/regolith-desktop#423]
**Describe the bug**
After installing i3xrocks battery package no battery icon is shown. 

**To Reproduce**
Upgrade to Ubuntu 20.04. Uninstall and re-install regolith. Install battery package:
```sudo apt install i3xrocks-battery```

**Expected behavior**
Battery should be shown

**Screenshots**

**Installation Details**
 - Regolith Install Type: Stable PPA
 - Regolith Version: 2.63-1focal1
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): [e.g. Ubuntu 20.04]

**Additional context**
Add any other context about the problem here. I have been having some other issues which may be relevant:
* Focused window name package also not working for me (i3xrocks-focused-window-name)
* The keybindings work, but the keybindings shortcut shows "no keybindings"
* Before I upgraded Ubuntu I had started having issues with older version of Regolith where nothing would be shown in bottom bar besides windows.

**Comment by kgilmer** [comment]
Hi @timgent , hmm, what do you get when running the battery script from a terminal?  (`/usr/share/i3xrocks/battery`).  Based on your 2nd point in additional context, I'm guessing that you have a custom i3 config file and it's not in sync with the latest default.  Have a [look here](https://regolith-linux.org/docs/getting-started/install/#upgrading-with-customizations) for details on how to update your i3 copy with the latest.

> Focused window name package also not working for me (i3xrocks-focused-window-name)
The fix for this is in `unstable`

> The keybindings work, but the keybindings shortcut shows "no keybindings"
Seems like your i3 config file is a copy and not up to date.

**Comment by timgent** [comment]
Thank @kgilmer, moving those old custom configurations out did the trick :) NB: That battery script was returning no output, but did seem successful (at least had 0 exit code). Everything is working now.

Btw thanks for all the work on a great tool. The improvements to the usability and docs over the last month look pretty ace :+1:
