### ISSUE TITLE
Integrate shutdown_menu

### ISSUE THREAD

**Issue by moritz-weber** [regolith-linux/regolith-desktop#45]
https://github.com/vivien/i3blocks-contrib/tree/master/shutdown_menu

This thing makes shutdown, reboot etc. much easier. Instead of memorizing different key combinations, I just open this menu:
`bindsym $mod+Shift+Delete exec ~/.config/i3blocks/shutdown_menu/shutdown_menu`

Btw: It looks amazing with your Rofi theme.

**Comment by kgilmer** [comment]
Dope! I will try it out this weekend and let you know what I think.  Thank you!

**Comment by dustinromey** [comment]
For what it’s worth, I have this set up on my machines. Works with the keyboard, not the mouse. To be specific, I can open the menu with the mouse, but the options in the menu only work with keyboard. 

It could be a config mistake on my part. 

I was able to pair it with the Font Awesome power icon very easily. Looks pretty good pretty easily.

**Comment by im7FFY** [comment]
Why don't you just use the commands `poweroff, reboot`? I think (tell me if I'm wrong), that the more you implement features, the more your system will be slower, and for the small (non existent?) improvement with this menu I don't think it's  a great move .

PS: English is not my native language, so sry if I write like  a 7 years old kid that might sound aggressive cause I'm def not, I just want to share opinion.

**Comment by moritz-weber** [comment]
> Why don't you just use the commands poweroff, reboot?

It really looks nice :smile: Then the actions became muscle memory. I just open it, hit the arrow keys a few times, then hit enter. I think, it's less (mental) effort than opening a terminal and typing the commands.

> the more you implement features, the more your system will be slower

In general, yes. If you open this menu only via keyboard shortcut though, it is only being called, when you need it. I am pretty sure, it won't affect general system performance.

(I just had to attach a screenshot, because I really like it :smile:)
![shutdown_menu](https://user-images.githubusercontent.com/17176771/59973238-3a2de080-959d-11e9-903b-c394f43f8469.png)

**Comment by kgilmer** [comment]
It does look very nice @moritz-weber .  I'm heads down on the Xresources effort but will look more closely at this once that's complete.

**Comment by kgilmer** [comment]
I have found that on some computers, pressing the power button causes a shutdown menu to appear, presumably from gnome-flashback.  I will do some more research into how we maybe able to use this built-in feature consistently, or integrate the rofi menu if not.

**Comment by kgilmer** [comment]
`gnome-session-quit` has options to specify logout, shutdown, and reboot.  When run we get a confirmation dialog that looks like this: 

![Screenshot from 2019-08-18 22-46-39](https://user-images.githubusercontent.com/49683/63241864-1b993e00-c20a-11e9-91ae-765d1cbfd3ac.png)

If I add desktop shortcuts for these three options, they are selectable from the standard Rofi menu.  

What I like about this approach
* confirmation dialog with timeout, option to lock screen
* uses system UI
* simple
What I don't like
* not as slick as a dedicated rofi menu

It would be also possible to add keybindings to these actions to perform the same activity.  In fact, the existing lout-out keybinding is not ideal because at times I hit it by accident and am instantly logged out of my session.

**Comment by brandondees** [comment]
I'd greatly appreciate a built in GUI or rofi menu for all these things, because out of the box I seem not to have trivial access to standby/hibernate options, locking screen with a keybinding is fine but I keep having to look it up each time because I don't have to do it often, etc.

It's touches like these that make regolith a _way_ nicer option for me than a DIY i3wm config, since I really don't always have the time for tinkering with that.

**Comment by kgilmer** [comment]
Thanks for the feedback @brandondees! Yes, we're working on this just this week in fact. We should have something soon.

**Comment by kgilmer** [comment]
I've had a bit of time to play with this.  The menu launched from the i3bar text works well, and the menu has every option a user would require for session management.  I do not like the idea of having menus being launched from the bar.  It's a perfectly fine UI approach, but for Regolith I want to keep the bar as a "read-only" UI construct, where as keybindings alone invoke mutable behavior.

Which brings me to the custom Rofi menu for session functions.  It took me awhile to be able to describe why I prefer the desktop actions over the custom menu: the custom menu adds UI "surface area" but, at least to me, doesn't really provide sufficient value to justify the new UI.  Meaning, grouping all of the various ways you can shut your computer down into one menu doesn't really add any value.  When terminating your session, you are unlikley to browse from a set of options.  Rather, you know what you need to do based on context and simply want to execute that action.  So, I feel that simply using Rofi launcher with actions, and keeping the same actions bound to the keyboard bindings is the best solution to this problem.

**Comment by kgilmer** [comment]
I should add that for those that like a dedicated Rofi menu for these functions, there is nothing about the solution I'm adding that would prevent or tarnish your custom menu in any way I can see.

**Comment by leosunmo** [comment]
I'm just playing around with an easier way of building Rofi menus and came up with a YAML-based system. Example of shutdown menu defined in YAML here: https://github.com/leosunmo/yofi/blob/master/shutdown-menu.yaml

Would love some input and if this is actually something useful for people.

If we're going down the route of building Regolith menus using Rofi we need to have a unified simple way of doing it.
