### ISSUE TITLE
Add rofimoji for quickly inputting emojis/unicode

### ISSUE THREAD

**Issue by codejeet** [regolith-linux/regolith-desktop#519]
**Is your feature request related to a problem? Please describe.**
Currently there is no easy way to input emojis in Regolith.

**Describe the solution you'd like**
Include [rofimoji](https://github.com/fdw/rofimoji) or a similar rofi script in Regolith. 

**Describe alternatives you've considered**
To mitigate this I've installed [rofimoji](https://github.com/fdw/rofimoji) on my personal machine.

**Comment by p3k** [comment]
i just installed rofimoji, too – and it’s the best emoji input for me so far. (although i made `ibus emojier` work, the window always was displayed in the very top left corner and i could use it with the mouse  only…)

@kgilmer what steps would be needed to add this to the regolith installer / package? what would be the preferred default key binding? (i’m using `$alt+shift+e`.)

**Comment by revarcline** [comment]
It would need packaging, which I might be personally interested in trying my hand at (never made a `.deb` before) and at least getting working on a ppa. It's a little tricky trying so far since rofimoji doesn't seem to have a standard setup.py file...

**Comment by p3k** [comment]
to revive this old thread: it seems rofi is now obsolete for regolith 2 (which is using its own desktop executor named ilia) – are there any ideas or suggestions to provide an emoji picker for ilia?

**Comment by revarcline** [comment]
i actually still use rofi in regolith 2 because i rely on rofimoji and greenclip too much, it would be cool to add those functionalities but i'm not about to learn vala lol

**Comment by kgilmer** [comment]
Yep, it was expected that some users would prefer to stick with `rofi`.  It's an awesome tool that has many uses outside of what was shipped in Regolith 1.x.  At this time it is not planned to integrate this sort of functionality into `ilia`, mainly just due to the amount of effort it takes to implement and maintain functionality over time.  If enough people ask for a way of extending `ilia` we may introduce a plugin hook, but that would require willingness for people to write their plugins in `vala` which doesn't seem to be the case here.  

For users looking for this sort of functionality, it is recommended to use `rofi`.  This can either be done wholesale (via installation of package `regolith-i3-rofi`) or simply adding new launchers to execute rofi via keybindings in a user i3 config partial.

**Comment by kgilmer** [comment]
Regarding @p3k 's question about how to add a rofi launcher to the Regolith i3 config, kindly see this documentation: https://regolith-desktop.com/docs/howtos/customize-i3-configuration/#how-to-customize-a-default-partial  The varaition here is that we just add a new partial, rather than copying and removing an old one.
