### ISSUE TITLE
Rofication stopped working

### ISSUE THREAD

**Issue by cheginit** [regolith-linux/regolith-desktop#528]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [x] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
After updating `i3xrocks-rofication` and `regolith-rofication` to version 1.3.0-1, it stopped working with the following error in `syslog`:
```bash
Traceback (most recent call last):
  File "/usr/bin/rofication-status", line 6, in <module>
    from rofication import RoficationGui, RoficationClient, resources, Resource
ModuleNotFoundError: No module named 'rofication'
```

**To Reproduce**
Update `rofication` to 1.3.0-1.

**Expected behavior**
`rofication` should install three executable files, `rofication-status`, `rofication-gui` and `rofication-daemon` but it seems that after the latest [commit](https://github.com/regolith-linux/regolith-rofication/commit/65393ce454f7248ef3308c90e8d0829d90d7bdd9) the `gui` and `daemon` ones are not installed.

**Screenshots**
NA

**Configuration file(s)**
No customization.

**Installation Details**
 - Regolith Install Type:PPA
 - Regolith Version: 1.5
 - PPA url: unstable
 - Host OS (for PPA): Ubuntu 20.10

**Additional context**
NA

**Comment by kgilmer** [comment]
I had made a poorly considered change to `regolith-rofication` that created a seperate binary package specifically for the i3xrocks conf file.  This change was intended to allow users to be able to uninstall the status indicator independently from the notification itself.  The problem was that the package build delegates to a python build system that does not integrate w/ the debian control file such that it is able to produce multiple binary packages.  Or at least, it's not obvious to me how that would work and I don't care to spend the remainder of the day in python build system wonderland.  

To resolve the issue I've moved the status indicator for rofication into the package `regolith-i3xrocks-config` as an independent binary package.  As this package does not use a python build system there are no problems w/ producing multiple packages.  I've had to add a `Breaks` declaration in `regolith-rofication` to ensure that `i3xrocks-rofication` is upgraded before `regolith-rofication` to avoid an install issue where both packages claim to "own" `/usr/bin/rofication-status`.  This potential issue should not have been an issue for users not consuming from `unstable` but can't be entirely sure, I've been surprised before.

Updates are building in `unstable` for testing.

I forgot to associate changes via commit message so here are the relevant changes:

https://github.com/regolith-linux/regolith-i3xrocks-config/commit/6dba99dce14c7f96ed8894fa16bff1b48dc21094
https://github.com/regolith-linux/regolith-rofication/commit/58918cd4825b40a256512e58398e5b95cae97f1a
https://github.com/regolith-linux/regolith-rofication/commit/13a61187e40161cf7e6dc6bfd1b51c40b1ffa496

**Comment by cheginit** [comment]
@kgilmer Thanks for the quick fix!

I have some experience with python packaging and IMO adding `entry_points` to `setup.cfg` works best:
```
[options.entry_points]
console_scripts =
	exec_name1 = package_name.python_file1:func_name1
	exec_name2 = package_name.python_file2:func_name2
```
Or to `setup.py`:
```python
setup(
    ...
    entry_points = {
        'exec_name1': ['exec_name1=package_name.python_file1:func_name1],
        'exec_name2': ['exec_name1=package_name.python_file2:func_name2],
        ...
    }
    ...
)
```
This will automatically generate standalone "shim"s and copy them to the Python bin directory. I am not entirely sure how it's going to work when used with the Debian packaging build system.

**Comment by kgilmer** [comment]
Thanks @cheginit :smile: .  I'll leave it for now but if I end up wanting to break a python build into multiple entry points I'll come back to this.
