### ISSUE TITLE
Change display options failed due to frozen certificate dialog

### ISSUE THREAD

**Issue by rootadminWalker** [regolith-linux/regolith-desktop#530]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [x] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
I'm using regolith desktop 2.105-1bionic on ubuntu 18.04.5. I've another monitor at my workspace. When I change the display settings, for instance from joining display to single display, I found the dialog saying 'Do you want to keep changes?' was transparent with no response, which makes it restore the old setting after 20s. 
Sometimes worse, it may accidentally log out with my unsaved jobs

**To Reproduce**
Press mod+d and change the display settings when you have multi-monitors

**Expected behavior**
the 'Do you want to keep changes?' dialog shouldn't be transparent and can be clicked to keep changes

**Installation Details**
 - Regolith Install Type: [PPA]
 - Regolith Version: 2.105-1bionic
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): Ubuntu 18.04

**Additional context**

**Comment by rootadminWalker** [comment]
I also have default ubuntu gnome installed alongside. If I urgently required to edit the setting, I'll need to log out, switch to gnome to change it

**Comment by moritzheiber** [comment]
This is _very likely_ a GNOME related issue (as the settings dialog is coming from `gnome-flashback`, together with `gnome-control-center`), paired with graphics drivers. My advice here would be the either try [the 18.04LTS HWE stack](https://ubuntu.com/kernel/lifecycle) or upgrade to the latest LTS release to (or further ahead) to get the latest changes.

**Comment by rootadminWalker** [comment]
Hi @moritzheiber, thanks for your advice! I've already installed ubuntu 18.04LTS HWE stack on my computer. I can't upgrade my os yet due to developing purposes. Is there any other way to solve this problem?

**Comment by moritzheiber** [comment]
Unfortunately, I don't think there is. Without an upgrade even filing an issue "upstream" (e.g. with `gnome-flashback`) is likely going to get rejected because the developer says you'll have to see whether the latest release of GNOME Flashback is going to solve your issue (which is not available to 18.04.x).

The only path forward without an upgrade would be to petition the Ubuntu developer on Launchpad to backport the GNOME Flashback releases to 18.04.x .. which is also highly unlikely to get enough attention :disappointed: 

I'm assuming you have `bionic-updates` and `bionic-backports` enabled as repository targets, right?

**Comment by rootadminWalker** [comment]
yes
