### ISSUE TITLE
Installing i3 clobbers stock i3 configuration

### ISSUE THREAD

**Issue by eric-s-raymond** [regolith-linux/regolith-desktop#544]
- [ Y] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [ Y] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [N ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
Installing Regolith from PPA clobbers the session-manager configuration for stock i3.  Uninstalling regolith-desktop does not undo this damage.

This behavior means there is no easy reversion to one's prior carefully tuned i3 setup if Regolith is unsuitable.  As it was for me; there were various usability bugs about which I may file separate issues if there is any action on this one.

It is rude and unacceptable to burn a user's bridge back to his old environment like that, especially without any warning from the installation documentation.  Now I'm going to have to play games with dpkg in attempting to recover that could destabilize my system further.

**To Reproduce**
Start with Pop!_OS configured with two session types. Pop and i3.  Install from PPA. Reboot.  Observe that the i3 session option is gone.

**Expected behavior**
I should have seen a Regolith type added to the session alternatives without clobbering the i3 session type.

**Screenshots**
None,

**Configuration file(s)**
I did not modify any configuration files before observing this bug.

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: [e.g. 1.4]
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): Pop!_OS 10.10.

**Comment by eric-s-raymond** [comment]
I was able to recover by uninstalling i3wm-gaps and reinstalling i3.  This procedure should be documented right after Install under "Getting Started" so users know they have a way out if things don't go well.

Note this article:

https://www.omgubuntu.co.uk/2019/06/install-regolith-linux-i3-gaps-ubuntu

which suggests at least one piece of additional fixup may be required.

**Comment by kgilmer** [comment]
Hello @eric-s-raymond , sorry to hear you had trouble with your setup.  Regolith relies on `i3-gaps` which, as an unofficial fork does not have independent files.  (they both produce an `/usr/bin/i3` executable, for example).  As such, when you installed Regolith from PPA, the package manager told you that it would be uninstalling `i3` to replace it with `i3-gaps`.  You may have better luck in general if you review what the package manager intends to do before proceeding with any software installation, and think twice if any software you rely on would be removed as part of such an operation.

In this case Regolith is working by design.  The comments in the link are to an older version of Regolith that are no longer relevant.

**Comment by eric-s-raymond** [comment]
It is a very bad idea to rely on package manager messages as documentation of something like this; there are a lot of them, they tend to go by fast, and doing lots of installations effectively trains one to type Y to prompts that usually don't mean this much.

I see that supporting both i3 and Regolith sessions is impractical, but surely the documentation should warn of the consequences and indicate a way out!  This is a terrible introduction to your project.
