### ISSUE TITLE
Tabbed keybinding

### ISSUE THREAD

**Issue by davidystephenson** [regolith-linux/regolith-desktop#55]
What is the keybinding for tabbed mode? `mod+w` does not seem to work.

**Comment by kgilmer** [comment]
Hi @davidystephenson, currently there is no keybinding for tabbed mode in the default Regolith i3 config.  `mod+w` should load the wifi config window.  How about `mod+t`?

**Comment by davidystephenson** [comment]
Thanks for the clarification @kgilmer. I remove that keybinding but it still does not work. I currently have nothing explicitly bound to `mod+w`. My config file located at `~/.config/i3-regolithh/config` is attached.
[config.txt](https://github.com/regolith-linux/regolith-desktop/files/3341868/config.txt)

**Comment by kgilmer** [comment]
Sorry, I was too brief in my previous question.  I was asking what keybinding you would like me to add for tabbed mode.  I personally didn't find it useful which is why I had removed it, but am happy to add it back in.  So, I was asking you if `mod+t` was a good keybinding in your opinion.  But, if you'd just like to configure it as `mod+w` that's fine too, and yeah just add the keybinding to your config and it should be fine.

**Comment by kgilmer** [comment]
I cannot add it back in as `mod+w` by default as that's already reserved for the wifi config function.

**Comment by davidystephenson** [comment]
`win+t` makes a  lot of sense to me. I think it would be good to have it somewhere. It gives good reason to document its status.

I'm actually quite new to i3 - how would I map it to `mod+t`?

**Comment by kgilmer** [comment]
The [i3 User Guide](https://i3wm.org/docs/userguide.html) is your friend!

To set mod+t for tabbed mode you can add something like this:
```
bindsym $mod+t layout tabbed
```

**Comment by davidystephenson** [comment]
Thanks for your help. I ended up with `bindsym $mod+t layout toggle splith tabbed`.

**Comment by kgilmer** [comment]
Glad to hear you got something working.  I'll close the issue but feel free to re-open if you're still having trouble.
