### ISSUE TITLE
How to remove Regolith

### ISSUE THREAD

**Issue by davidh38** [regolith-linux/regolith-desktop#564]
I am using I3 and just wanted to try regolith. I saw, that it did not meet my purpose (dvorak standard keys were used, which does not make sense to any dvorak user, i would say and weirdly not using alt as super key, even when changing the super key getting error messages etc., but no problem), so i just want to remove regolith and go back to my standard i3, at least for now, because i want to use my system.

 Not only that i cannot go back to my i3 standard configuration in ubuntu, i am not able even able to remove regolith. How to remove this??? Why does it not tell in the documentation, how to remove rigolith, if it is not easily done by just sudo apt remove desktop-rigolith? I feel like, i am getting punished to have tried it, though this configuration seems to be a good solution for me, but not adhoc, because the standard configuration is bad for me.

**Comment by kgilmer** [comment]
Hi @davidh38 , sorry to hear you're having trouble removing Regolith.  I'm happy to help you as best I can to get your system back to a state without Regolith.  Here are the instructions for uninstallation: https://regolith-linux.org/docs/getting-started/install/#uninstallation-of-regolith-desktop

Note that the desktop package varies based on what you installed.  So rather than `regolith-desktop` substitute the package you installed, probably `regolith-desktop-standard`.  If you continue to have problems, please give specific details.  Paste the error messages you receive and the command you entered into this ticket so I can understand what's going on on your system.

**Comment by davidh38** [comment]
Hello kgilmer,
thanks, i could remove regolith by
sudo apt purge regolith-desktop && sudo apt autoremove
which also deinstalled my i3 standard. Thank you for the help.
