### ISSUE TITLE
Smoother install process for standard i3 users on ubuntu 20.04

### ISSUE THREAD

**Issue by davidh38** [regolith-linux/regolith-desktop#566]
I suggest the following to improve this awesome product:

A smoother experience for i3 users who want to try regolith: it should be installing it and either have the possibility to go back to i3 standard or easily remove it without removing your i3 installation

**Comment by kgilmer** [comment]
Yes, it's a good suggestion.  This problem will be better to some degree in Regolith 2.0, as the user will have the option to run `i3` or `i3-gaps` based on their preferences.  The root-cause of this issue is that `i3-gaps`, being an unofficial fork, uses the same file layout as `i3`.  So, they cannot be both installed on a given system at the same time.  When you go to install `regolith-desktop-???` it pulls in `i3-gaps` which conflicts with `i3` which causes `apt` to uninstall i3.

In any case we will add some better docs about this situation in the installation guide.
