### ISSUE TITLE
i3-snapshot broken dependency libjsoncpp1

### ISSUE THREAD

**Issue by mhalano** [regolith-linux/regolith-desktop#585]
- [X] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [ ] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
I tried to install the `i3-snapshot` package on Ubuntu 21.04, but I got an unmet dependency. The package depends on `libjsoncpp1` but for this Ubuntu release just the package `libjsoncpp24` is available.

**To Reproduce**
On Ubuntu 21.04 try to install `i3-snapshot` package.

**Expected behavior**
Installation without issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/6025031/123270945-ba61e600-d4d6-11eb-8650-77f587457918.png)

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 1.6
 - PPA url: ppa:regolith-linux/stable
 - Host OS (for PPA): Ubuntu 21.04

**Comment by kgilmer** [comment]
thanks for your bug report @mhalano .  I have reproduced it.  It may take some time to resolve, it's unclear to me why this dependency is broken in hirsute.  I do not explicitly depend on any version of libjsoncpp so I don't know why apt is giving this error.

**Comment by mhalano** [comment]
I was unable to build a package from source, so my best guess is your dependency from libjsoncpp-dev is resolved to the adequate package. The problem is in a newer Ubuntu version, the package name changed from libjsoncpp1 to libjsoncpp24. It's a little strange since the version for the application still is 1.9, so seems to me should keep the name. But an API break change could happen during development. Could you try to build the package with a newer distro release?

**Comment by DaBlitzStein** [comment]
Looks like this library is not available on ubuntu 21.
https://bugs.launchpad.net/ubuntu/+source/libjsoncpp/+bug/1928695

**Comment by khos2ow** [comment]
I also had similar issue on a fresh install of 1.6 with ISO. On the other hand there was no issue when upgrade another machine from 1.5 to 1.6.

I ended up directly installing via `.deb` file found [here](https://www.ubuntuupdates.org/package/core/groovy/main/base/libjsoncpp1).

**Comment by kgilmer** [comment]
It is indeed a major thing @DaBlitzStein .  This issue puzzles me because I would not expect packages to be removed from a released Ubuntu repository.  I'm certain this dependency was available at the time of release otherwise I would not have been able to test on Hirsute via PPA.  In fact the ISO builder would not have been able to complete succesfully either.

The package `i3-snapshot` does not depend on the older version of `libjsoncpp` so changing the dependency is not an option.  I'm going to attempt to re-build in launchpad specifically for `hirsute` and see if that fixes it.  If not, I will have to remove the dependency on `i3-snapshot` unless another solution presents itself.

**Comment by kgilmer** [comment]
Rebuilding the package specifically for `hirsute` has resolved the dependency issue in my testing.  I will promote this package to `stable` and `release` from `unstable`.  This usually takes an hour or so.  Once that's complete @mhalano or @DaBlitzStein , perhaps you could test and confirm the issue is resolved for you as well?

**Comment by mhalano** [comment]
I can confirm the package was installed correctly.

**Comment by kgilmer** [comment]
Great, thanks for testing @mhalano
