### ISSUE TITLE
regolith-desktop on Debian should not depend on mutter-common

### ISSUE THREAD

**Issue by ploum** [regolith-linux/regolith-desktop#619]
The package "regolith-desktop-mobile" depends on "mutter-common".

It looks like this dependency is unnecessary and a bit confusing (mutter, as far as I know, a Wayland WM now)

**Comment by kgilmer** [comment]
It is a dependency in Ubuntu because of [this patch](https://salsa.debian.org/gnome-team/gnome-control-center/-/blob/ubuntu/master/debian/patches/ubuntu/display-Allow-fractional-scaling-to-be-enabled.patch).  But, you're right that it should be removable in the Debian version of Regolith.

See https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/977

**Comment by kgilmer** [comment]
Fixed by https://github.com/regolith-linux/package-repo/commit/8f263cfa921c9f1404d1d38a71cde916dff4ff74
