### ISSUE TITLE
regolith wallpaper is blurry after upgrading to regolith 2.0

### ISSUE THREAD

**Issue by ploum** [regolith-linux/regolith-desktop#630]
I had configured Regolith 1.6 to not have any wallpaper in order to have a black background.

I upgraded to Ubuntu Jammy without upgrading Regolith and something strange happened : the background was now the lightdm background in my session (with the stars) instead of the black background.

After upgrading to regolith 2.0, the background itself became blurry.
![regolith_wallpaper](https://user-images.githubusercontent.com/1233155/161447265-90b95dd3-b690-4f09-af03-4a152cc31cdb.png)

**Comment by ploum** [comment]
note that "regolith-look set nord" changed the wallpaper. "regolith-look set default" keeps the nord wallpaper (maybe on purpose)

**Comment by kgilmer** [comment]
Wallpaper handling is somewhat complicated, due to the attempt to converge two styles into one:

1. specify wallpaper via dotfiles (in our case Xresources)
2. specify wallpaper via gnome

If a look sets a wallpaper, the Regolith session will call `gsettings` to set the wallpaper to whatever the file specified by `gnome.wallpaper` Xresource is set to.  If a look does not specify a wallpaper, no action is taken.  This has the side effect that switching to looks without wallpaper will cause a previous wallpaper to stick.  If the user directly changes the wallpaper via gnome-control-center or gsettings, Regolith will not make any change until/if: 

1. regolith-look refresh is called, reloading anything that was set by Xresources
2. another look is installed which specifies a new wallpaper

There is another aspect to this that if the image file that wallpaper settings was using is deleted (for example you uninstall a look that had been hosting the image), the wallpaper will revert to some varation on what is specified in the dconf defaults for that value, specified here: https://github.com/regolith-linux/regolith-default-settings/blob/master/debian/regolith-default-settings.gsettings-override#L22

Reasoning about wallpapers is difficult in Regolith because of these two styles that we try to work with (dot files vs dconf), but I don't see a better solution. LMK if you can think of a way to support these two modes in a simpler or more consistent manner..

**Comment by ploum** [comment]
My take on this is that GNOME makes wallpaper handling really complicated (not to mention the fact that is now impossible in GNOME to *not* have a wallpaper). GNOME expects to run alone, fully. And Regolith is trying to break that into pieces. Something GNOME doesn’t want.

This means that there’s a hard decision to take but the sooner, the better. This is really a decision that needs to be taken. Not taking the decision is imposing the user to make it. Which is the current situation and why things are so hard.


1) First choice: 

Keeping GNOME wallpaper and forbiding themes to set a wallpaper. That makes senses. In nearly every system, wallpaper is unrelated to the theme. Wallpaper is the first thing you change anyway.  

To make this change clear, any command line way to change the wallpaper outside gnome should be removed. The gsettings approach should be used. This makes Regolith a clear GNOME modification which follows more the GNOME philosophy. 

2) Second choice:

Removing entirely GNOME wallpaper handling from the new regolith-control-center. Wallpapers should be set through a command (a "regolith-wallpaper" command might be created). Theme could define their wallpaper but switching to a theme without wallpaper should probably set the default wallpaper.  Or wallpaper can be removed from theme, like in solution 1.


I feel that the choice is a philosophical one. Is Regolith aimed at non-command-line users to make them discover tiling-manager? Or is Regolith aimed at somewhat power-users to make their life easier?

(Disclaimer : I’m of she second category)   My observations are that Regolith seems to target more the second philosophy. There are already documented command line without GUI (like regolith-look). The fork of regolith-control-center is also to me a sign that Regolith is trying to get away from the GNOME monolith, taking only what is really useful/needed (and setting the wallpaper clearly isn’t part of the good parts of GNOME).  But, of course, choice is not mine to make and I’m only opening a dicussion here.

**Comment by kgilmer** [comment]
I'm still working through various approaches to the problem.  Ideally we could address both user cohorts in such a way that they work without conflict.  A core cultural element to Regolith is inclusivity, and so we would like to keep things easy for less technical users when possible.

  The missing state that is needed is: any any given point in time, is the current wallpaper specified by a human (eg via control center or xres override) or was it set by a theme (via Xres override or direct gsettings).  If this state is available, I believe the following heuristic is consistent across both user cohorts:

1. any time that a program may wish to change the wallpaper, if the wallpaper has been set by a human, do not change.  Otherwise change.

In this way looks can specify wallpapers.  Users can set wallpapers.  Once a user has set a wallpaper it is never modified by Regolith.  However once a user sets a walllpaper it doesn't seem that this mode can be unset and so they forever miss out on any default wallpapers.  

And then I go back to your thoughts ~

> In nearly every system, wallpaper is unrelated to the theme. Wallpaper is the first thing you change anyway.

In thinking about how gnome handles wallpaper, this seems consistent with your view.

Perhaps the ideal solution is simply to remove wallpaper specification from looks, or possibly make them opt-in in some way, although I can't think of a UX that like.

**Comment by ploum** [comment]
Thought about it and here are my 2 cents:

As there’s now a "regolith-control-center", let’s rewrite the "wallpaper tab" of it to do the following:

1. The tab allow to select a theme (and thus act as an interface to regolith-look
2. There’s a dropdown : "no wallpaper/uses theme wallpaper/custom wallpaper"
4. If not custom wallpaper, the part bellow is greyed out.
5. The part below is a simple wallpaper chooser to allow configuring the wallpaper.

Behind the scene, the wallpaper setting uses a simple command-line (xsetroot? feh?) which is saved in a regolith startup file somewhere in .config/regolith2.  That means that changing wallpaper in your config (or restoring a backup) plays well with the GUI.

It is also clear that the user want or doesn’t want the theme wallpaper (if theme as no wallpaper, fallback to default).

Last but not least, the "no wallpaper" allow user to configure itself through .xsession (regolith doesn’t read .xsession but I guess it is another, unrelated bug)

Nice bonus : porting the whole thing to wayland is as trivial as changing the xsetroot command

**Comment by ploum** [comment]
it seems that the bug is back with the refactoring of the themes (it may have been hidden because of my wallpaper but my wallpaper disappeared with the upgrade)

**Comment by georglauterbach** [comment]
I'm having trouble setting the wallpaper as well with R2. The default wallpapers seems to work fine, but my user-defined one does not work.

**Comment by kgilmer** [comment]
I've tested these scenarios in Beta 1:

## Update wallpaper and refresh

1. specify wallpaper by adding the following to [`~/.Xresources`, `~/.config/regolith2/Xresources`]:
```
regolith.wallpaper.file: /usr/share/backgrounds/El_Haouaria_by_Nusi_Nusi.jpg
```
2. Refresh look via keybindings
3. Observe wallpaper changed

## Update look and refresh
1. specify wallpaper by adding the following to [`~/.Xresources`, `~/.config/regolith2/Xresources`]:
```
regolith.wallpaper.file: /usr/share/backgrounds/El_Haouaria_by_Nusi_Nusi.jpg
```
2. Select another look via look selector
3. Observe wallpaper loaded is what is specified in Xresources, not the look

I'm not aware of any other test scenarios that would need to be tested.  Kindly reopen if there are still problems.
