### ISSUE TITLE
there is absolutely no way of simply just changing your theme to other colors without a hassle. on both 1.0 and 2.0.

### ISSUE THREAD

**Issue by peejxyy** [regolith-linux/regolith-desktop#661]
as you can tell my the title, you are unable to make your own colorscheme. no matter how hard i tried, i could not edit it through the config file, like normal i3 users do. i tried making a blank folder into the styles folder, so no regolith looks override it, and it doesnt work. really bummed out by this is because i want to use the one dark colorscheme, but i cannot. im suprised they didnt add this in 2.0. hopefully in the future.

edit: i finally found out, but its complex. i still cant just use the config file for easier change of the color scheme, but it is possible to change the colorscheme, by editing an already regolith look you have installed.

**Comment by 123vivekr** [comment]
I felt this problem today. Wasted some time editing i3config and got confused but finally understood the flow.

For now, I just fork and modify an existing regolith "Look".

**Comment by kgilmer** [comment]
In Regolith colors are defined in two places: GTK themes and color definitions specified in Looks as Xresource key/values.  In Regolith 2.0, to customize a look, a new one can be copied from an existing look for modification:

```
sudo cp /usr/share/regolith-look/default /usr/share/regolith-look/my-look
```

From there edit the file `/usr/share/regolith-look/default /usr/share/regolith-look/my-look/root` to specify alternative gtk themes and color definitions.  To test it out select via the command line `regolith-look set <name>` or using the Look selector dialog.

In Regolith 2.1 it will be possible to have user Looks that live in `~/.config/regolith2/looks/`.

This issue is more of a statement of frustration rather than an actionable problem.  Feel free to suggest updated or provide PRs to [the docs](https://github.com/regolith-linux/regolith-desktop-website/blob/main/content/docs/using-regolith/configuration.md) for customization if you have any. :peace_symbol:
