### ISSUE TITLE
Regolith default look suddenly has altered colors. 

### ISSUE THREAD

**Issue by Yimellovzski** [regolith-linux/regolith-desktop#705]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues) (don't want to.)

**Describe the bug**
Regolith changed its default look to an ugly combination of colors after I updated from 2.0 to 2.1. I tried uninstalling, purging regolith files and OS flashing and still there appears to be no way to revert back to the colors default regolith look should have. 

**To Reproduce**

I have no idea what caused this or the steps to reproduce it.

**Expected behavior**
...

Default regolith look should look like this:
![regolith-ilia-keybindings](https://user-images.githubusercontent.com/45341995/185764872-b5e1bba5-44b5-46a1-b3fb-cf6e19c44d05.png)

Instead of this:

![Screenshot from 2022-08-20 16-19-40](https://user-images.githubusercontent.com/45341995/185764876-41468eb6-388e-48ec-8803-c18efc0af0a3.png)

**Screenshots**

read previous section.

**Configuration file(s)**
I'm somewhat new to this desktop environment (~1 month) so I have no clue where the configs are.

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: Latest (2.1)
 - PPA url: ppa:regolith-linux/release
 - Host OS (for PPA): Pop!_OS 22.04

**Comment by Yimellovzski** [comment]
Update: I spent hours doing research and managed to make a close copy of the default look as it should be, took most of the elements from lascaille's look which is one of the better ones out there.

![Screenshot from 2022-08-21 01-05-09](https://user-images.githubusercontent.com/45341995/185776356-119da4e6-f801-48f6-be91-1cb678c2a3f4.png)

**Comment by kgilmer** [comment]
Hi @Yimellovzski !

> I have no idea what caused this or the steps to reproduce it.

This was a result of a change between Regolith 2.0 and 2.1.  In order to make it easier to port Regolith to other distros, the default session should depend on as few packages as possible.  So, some changes were made to further simply the default session.  However the gtk resources are not refreshed until `regolith-look refresh` is called, either manually, via keybinding, or as a result of selecting a new look via the Look Selector.  And so you may have upgraded but not seen the visual update until well after.

  In case you're interested, this change was (briefly) mentioned in the release notes: https://regolith-desktop.com/docs/reference/Releases/regolith-2.1-release-notes/#changes-in-regolith-look-default

I'm happy to see you were able to setup your own look to your liking.  In case you're not aware, other looks such as lascaille (my favorite too :) ) can simply be installed as packages and then selected via `super` `alt` `l`.  eg

```console
$ sudo apt install regolith-look-lascaille
```

To see all official looks:

```console
$ apt list | grep regolith-look-

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

regolith-look-ayu-dark/unknown,now 0.8.4-1regolith amd64 [installed]
regolith-look-ayu-mirage/unknown,now 0.8.4-1regolith amd64 [installed]
regolith-look-ayu/unknown,now 0.8.4-1regolith amd64 [installed]
regolith-look-blackhole/unknown,now 0.8.4-1regolith amd64 [installed]
regolith-look-default/unknown,now 0.7.1-1regolith amd64 [installed]
regolith-look-dracula/unknown,now 0.8.4-1regolith amd64 [installed]
regolith-look-gruvbox/unknown,now 0.8.4-1regolith amd64 [installed]
regolith-look-i3-default/unknown,now 0.8.4-1regolith amd64 [installed]
regolith-look-lascaille/unknown,now 0.8.4-1regolith amd64 [installed]
regolith-look-nevil/unknown,now 0.8.4-1regolith amd64 [installed]
regolith-look-nord/unknown,now 0.8.4-1regolith amd64 [installed]
regolith-look-solarized-dark/unknown,now 0.8.4-1regolith amd64 [installed]
```

**Comment by Yimellovzski** [comment]
Thanks for the clarification! I did not know about those changes, will make sure to backup my local configs next time. And I appreciate the tip! Closing this issue now.
