### ISSUE TITLE
Pub key not avaible on https://keyserver.ubuntu.com/

### ISSUE THREAD

**Issue by pietryszak** [regolith-linux/regolith-desktop#746]
Can anyone explain me why pub key is not stored in https://keyserver.ubuntu.com/.
Old regolith 1.6 was avaible but new 2.0 not.
Old kind of key propagation is much more better, esspecialy when we install regolit by ansible script

Old key for 1.6
![image](https://user-images.githubusercontent.com/45850093/195828896-7ed38aac-bb64-4062-8f03-f2b1a3e1470a.png)

Key for 2.0
![image](https://user-images.githubusercontent.com/45850093/195829057-4ae12884-f2a5-4267-bb5c-4c3fa1e4f09f.png)

**Comment by kgilmer** [comment]
Hi @pietryszak , the 1.x key was registered with launchpad.net.  Due to scaling and reliability issues w/ package builds we opted to move away from using launchpad for builds and package hosting.  Unrelated, a new key was generated, I think because of lost password. I'll look into registering the new key w/ Launchpad as well, if that would help on the ansible stuff.

**Comment by pietryszak** [comment]
It's just faster, everything working just respected when key is outside launchpad 😁

**Comment by kgilmer** [comment]
Should be fixed
