### ISSUE TITLE
Regolith ignores default configuration file path?

### ISSUE THREAD

**Issue by tiritto** [regolith-linux/regolith-desktop#78]
It seems that whenever I change something in my `~/.config/i3-regolith/config` file and relog, all settings go back to default state. I also noticed that new `config-4.16-1ubuntu18ppa10` showed up and apperantly this is considered as proper config file. I'm not very advanced linux yet, so this confuses me a little.

On Regolith website How To section contains information about creating new keybindings and apperantly it uses just standard `~/.config/i3-regolith/config` path, despite the fact it doesn't really work anymore as configuration is applied from another file.

I noticed that new configuration in `config-4.16-1ubuntu18ppa10` is clearly an updated, much more modular version of the configuration, so I figured out it's just the result of an update. But how am I supposed to make changes to my i3 configuration now? Should I just edit new config file instead? Is there any way to force using previous, much cleaner path `~/.config/i3-regolith/config` other than making symbolic link?

**Comment by UtahDave** [comment]
Yeah, I just noticed this as well because I remap my super key to left alt.

This was an unexpected change. Was this change on purpose?

**Comment by kgilmer** [comment]
Hello @tiritto and @UtahDave , sorry for the confusion.  `config-4.16-1ubuntu18ppa10` is now the default i3 config file, as of yesterday.  This was a planned change.  In essence, the configuration file changed a lot to support using Xresources to load color values.  When making this change, I did not want to over-write existing i3 config files, because I knew people (such as yourselves) have made changes and didn't want to destroy them.  So instead, the strategy I came up with is to version the i3 config file along with the package.  This requires you to manually merge back in your changes after an upgrade.  I realize this is a pain and will minimize how often this happens.

Some of the documentation has not been updated to reflect the new configuration.  I'll work on that this week.

@tiritto I suggest you use a visual merge tool to selectively take in the changes you want from `~/.config/i3-regolith/config` into `config-4.16-1ubuntu18ppa10`.  vscode has a nice visual merge tool, if you don't already have a favorite.  If you install vscode, to perform a visual merge type:
```
cd ~/.config/i3-regolith
code --diff config-4.16-1ubuntu18ppa10 config
```

And you'll see something like this, which makes it easy to see changes and selectively take whichever you like and leave the rest:

![Screenshot from 2019-07-30 10-12-01](https://user-images.githubusercontent.com/49683/62150331-97126a00-b2b2-11e9-99bd-0b71c24c251d.png)

This is just one way of merging your changes in, however, and may not be the ideal or prefferable way.  Just one approach.

**Comment by UtahDave** [comment]
Thanks for the update @kgilmer !  

Is there an announcement email list or something where I could find out about these kinds of changes beforehand?

**Comment by kgilmer** [comment]
@UtahDave that's a great idea!  I'll create one and move the "news" there instead on the site.

**Comment by leosunmo** [comment]
Got confused by this as well, `ps -ef | grep i3` at least helped!

On a somewhat related note, thoughts on a Slack channel for Regolith Linux, @kgilmer ?
It would be great to be able discuss some of these things as well as get/give live help to some of the newcomers to linux (go @tiritto !! This is the right move!).

For me personally it'd be nice to be able to quickly jump in and help people as well as try to stay up to date. The project is quite spread out now across many repos, so it's tough to keep up. I'd also like to contribute as much as I can, but I usually don't have time to seek out a specific issue, so it'd be nice if there was a more direct way to ask how I can help.

I don't mind setting up the Slack channel initially if you don't want to deal with that, Ken.

**Comment by kgilmer** [comment]
* All references to the old config file have been fixed on the site.
* A mailing list has been setup so people can get notified of changes (see https://regolith-linux.org/news.html)
* A basic roadmap for active and future work has been added to the news page.

**Comment by kgilmer** [comment]
Hi @leosunmo , that would be a great help, thank you!  I don't have any strong opinions on specific chat provider.  Let me know what you get setup and I'll add it to the site for others to find.

**Comment by dustinromey** [comment]
Just to point out for anyone else following on along at home, the list
provider also provides an RSS feed for those of us stuck in 2010 at:
https://www.freelists.org/feed/regolith-linux

Preferred for me by RSS, so that's great. But I'm happy to give a Slack
channel a try as well, since its all the rage.

**Comment by tiritto** [comment]
Speaking of extra communication channels, a lot of FOSS projects also have their own subreddits. Maybe it would be a good idea to create subreddit for Regolith Linux as well? In fact, **r/regolith** seems to be available for anyone who just decide to claim it.

Reddit is quite popular platform and having own subreddit opens the way for community to interact with each other more often, in the effect spreading awareness of this project. You could add flairs that can be assigned to new posts to keep it clean and more organized. For example:

- Announcement or PSA for all kind of announcements regarding Regolith Linux, like updates.
- Help, Question or Problem for people having some kind of issues or just need some help.
- Discussion for general talk about Regolith and/or it's development. Could be also used as feedback.
- Showoff for people who would like to share screenshots of their riced Regolith along with dotfiles.

On top of all that, it would be also much easier to redirect people from other subreddits when they have Regolih-related issues, by simply linking them Regolith subreddit.

And for more live-oriented help and discussion I think slack is indeed good choice, although some people might prefer Discord over slack. Either way, for people in dire need of instant help it wouldn't really matter what platform is used, as long as it's active.

**Comment by tiritto** [comment]
In regard to new configuration path, everything is clear now and I totally see why you decided to resolve it this way. However, I am a bit curious about one thing here. Wouldn't it be easier and more intuitive to just rename already existing `~/i3-regolith/config` file to something like `~/i3-regolith/config.old` or `~/i3-regolith/config.pre4.16-1ubuntu18ppa10 and then write new configuration back into `~/i3-regolith/config`?\

It seems that you would achieve the same result: old configuration file is not being deleted and new configuration file is taking place of outdated one. On top of that, it has additional advantage of easier path to remember, it keeps the "default" configuration path that people are already familiar with if they used i3 before, and it keeps the path to the newest configuration always unchanged, which I imagine might be useful in case of some scripts.

Or am I missing some crucial detail in this current approach?

**Comment by leosunmo** [comment]
This is getting a bit off-topic, but Regolith-Linux slack is live! https://join.slack.com/t/regolith-linux/shared_invite/enQtNzEyNDM3MTgwNTc2LWQ2YmIzYTJjNmYxNzcwYThiMDM4NDRiZDY2OTkwMmE2NjI1OWQyNmQ5ODhlODIyYWNmZTZlNjQ3N2M1NmJiMWI (expires in 30 days)

**Comment by kgilmer** [comment]
@tiritto ~
Reddit: yes, it's a good idea.  Thanks for providing the summary and advantages, very helpful.  At this point I have limited time to work on Regolith so I need to be careful about what I spend time doing.  I'm weary of having too many "things" to monitor, respond to, keep updated, etc..   If I used a subreddit then I would probably not want to use the mailing list also.  I'm not a Reddit power user.  Do people subscribe to notifications of new posts?  I'm thinking people would not want to hear everything anyone will say about it, but probably rather just get announcements of upgrades and go to the reddit if they have a problem.  Do I have it wrong?  In any case i3wm and unixporn I visit often so I do like the idea, but do not want to duplicate or complicate the function of the mailing list.

On renaming config files vs creating new ones:  You have some good points.  There are really two perspectives ~ the perspective of the package maintainer (me, at this point in time), and the user.  From the user's perspective, it's absolutely better to use the same config file rather than creating new things.  However from the perspective of the system, as soon as you have scripts that delete and/or move things, you open up the potential to lose user data.  If you only ever write new files, then, while complicating the system with more files, you do not have to worry about destroying data.  So, it does put some burden on the user, to understand where the files are.  But, I can feel better that a bug I add will not destroy your custom configuration files.  To be honest, I'm not happy with either approach.  I would like a system that allows us to express at update time what is happening and why, and give the user options.  Debian has a facility like this for /etc files which I considered using as well.  But, the tooling is pretty esoteric and I don't feel that it's easy enough to use to be generally useful.  I am trying to find the sweet spot in Regolith between "power user" and "i3 neophyte".  I'm not sure that I've found it.  

@leosunmo that's awesome, thanks!  I'll join in soon!

**Comment by kgilmer** [comment]
Thanks again for setting up that Slack channel @leosunmo .  I just tried to join, in Chrome I get some poorly rendered page without any CSS (m76) or actionable steps and on Firefox 68 I get good pages but there is some kind of race condition in the JS sign in page, I am unable to enter a password.  I'll try again tonight.

**Comment by leosunmo** [comment]
Huh, that's weird. Looks to be working fine now. Slack might have had issues. I had someone else join, so the link does work at least sometimes!

**Comment by kgilmer** [comment]
Something is wrong with my desktop.  I was just able to sign in with my laptop so I'm in, thanks!  :smile:

**Comment by kgilmer** [comment]
Assuming original issue is resolved.  Please re-open if this is not the case.

**Comment by ENate** [comment]
Great to discover regolith. But as a first time user on Ubuntu 18.04, I noticed that vpn doest not work. I read that someone already raised the issue. But I cannot find the /home/myname/.config/regolith/i3/config file. Do I have to install i3wm in order to acess the regolith i3 config file? Could anyone let me know where to find this file? I Currently, I only see $HOME/.config/regolith/flags under the regolith config directory. Do I have to create the ~./config/i3-regolith/config? I cannot even find any i3-regolith.

**Comment by juan-serrano-soria** [comment]
> Great to discover regolith. But as a first time user on Ubuntu 18.04, I noticed that vpn doest not work. I read that someone already raised the issue. But I cannot find the /home/myname/.config/regolith/i3/config file. Do I have to install i3wm in order to acess the regolith i3 config file? Could anyone let me know where to find this file? I Currently, I only see $HOME/.config/regolith/flags under the regolith config directory. Do I have to create the ~./config/i3-regolith/config? I cannot even find any i3-regolith.

I know this isn't remotely close to a good fix, but since I have had the same problem (couldn't find the config file either) and I needed to use my university VPN, I came up with this improvised solution, which isn't really that bad for a quick fix:

The first time you boot your pc, log in on gnome, activate the vpn, log out and log in on regolith. The vpn should work fine, and you can deactivate it too from regolith, although you would not be able to activate it back.
If you don't want to have the vpn on all the time, you can always do a quick log out -> log in gnome, log out -> log in regolith, whenever you need it.

**Comment by kgilmer** [comment]
Unfortunately I don't have a VPN to test with.  Thanks for the tip @juan-serrano-soria !  @ENate , sorry I did not see your message on this ticket.  You do not need to install anything to access the i3 config file.  It is only in your user directory if you copy it there, otherwise it's in `/etc/regolith/i3/config`.  You can find out for sure what i3 config file is being used by running `i3 --moreversion` from a terminal.  For further details regarding the i3 config file, see here: https://regolith-linux.org/docs/reference/configurations/

**Comment by ENate** [comment]
Thanks @kgilmer  and awesome stuff you and the team did/are doing. It is seamless to use except that in trying to extend to 2 monitors, one cannot move open applications like you will normally do in a typical GNOME environment. Is there anything that can be done to this end? Will also like to be part of the team (to contribute in some way later).
But given that it consists of the i3 components, it is not difficult to see why moving open applications to 2 monitors like a GNOME might be impossible to achieve. Besides, I also found out that trying to equally tile 4 windows on same screen might be difficult too. Though all 4 windows will open, it automatically tries to set the sizes. I will expect that the space assigned to 4 windows should be equal with two open applications directly appearing about each other. Maybe I am wrong.

**Comment by kgilmer** [comment]
Hi @ENate , looks like you're looking for [floating window mode](https://i3wm.org/docs/userguide.html#floating_modifier).  In Regolith to make the focused window floating, use `<super><shift>f`.

To create 4 terminals in a 2x2 grid, perform the following key sequence on an empty workspace:

`<super><enter>`
`<super><enter>`
`<super><backspace>`
`<super><enter>`
`<super><left>`
`<super><backspace>`
`<super><enter>`

![image](https://user-images.githubusercontent.com/49683/79644285-d04e7b00-815c-11ea-8d52-45b2630e07d0.png)

**Comment by kgilmer** [comment]
Also, we'd love the extra pair of hands if you're looking to get involved.  Feel free to join us in the regolith-dev room in the Regolith slack.
